{
 "title": "NDM - Go process stats",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Process Memory In MiB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=\"default\"}",
     "legendFormat": "Resident memory: {{kubernetes_pod_name}}"
    },
    {
     "expr": "process_virtual_memory_bytes{namespace=\"default\"}",
     "legendFormat": "Virtual memory: {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Open File descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{namespace=\"default\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Statistics",
   "type": "graph",
   "description": "Heap, Stack and Total memory allocated to a Go process at the specified time.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{namespace=\"default\"}",
     "legendFormat": "Total allocated memory in  {{kubernetes_pod_name}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{namespace=\"default\"}",
     "legendFormat": "Stack memory in {{kubernetes_pod_name}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=\"default\"}",
     "legendFormat": "Heap memory in {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{namespace=\"default\"}",
     "legendFormat": "{{kubernetes_pod_name}} with quantile {{quantile}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{namespace=\"default\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}