{
 "title": "Go process stats & Services Availability",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(kube_pod_info,cluster_name)"
   }
  ]
 },
 "panels": [
  { "title": "Services Availabiity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Auth",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=\"default\", pod=~\".*auth.*\", cluster_name=~\"$ClusterName\"}"
    }
   ]
  },
  {
   "title": "Access control",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=\"default\", pod=~\".*accesscontrol.*\", cluster_name=~\"$ClusterName\"}"
    }
   ]
  },
  {
   "title": "Dproxy",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=\"default\", pod=~\".*dproxy.*\", cluster_name=~\"$ClusterName\"}"
    }
   ]
  },
  {
   "title": "Executions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=\"default\", pod=~\".*executions.*\", cluster_name=~\"$ClusterName\"}"
    }
   ]
  },
  {
   "title": "Streams",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=\"default\", pod=~\".*streams.*\", cluster_name=~\"$ClusterName\"}"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=\"default\", pod=~\".*subscriptions.*\", cluster_name=~\"$ClusterName\"}"
    }
   ]
  },
  {
   "title": "Terms",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=\"default\", pod=~\".*terms.*\", cluster_name=~\"$ClusterName\"}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=\"default\", pod=~\".*transactions.*\", cluster_name=~\"$ClusterName\"}"
    }
   ]
  },
  {
   "title": "UI",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=\"default\", pod=~\".*ui.*\", cluster_name=~\"$ClusterName\"}"
    }
   ]
  },
  { "title": "HLF Services Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Orderer",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=\"blockchain\", pod=~\".*orderer.*\", cluster_name=~\"$ClusterName\"}"
    }
   ]
  },
  {
   "title": "Peer-0",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=\"blockchain\", pod=~\".*peer0.*\", container=\"peer\", cluster_name=~\"$ClusterName\"}"
    }
   ]
  },
  {
   "title": "Peer-1",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=\"blockchain\", pod=~\".*peer1.*\", container=\"peer\", cluster_name=~\"$ClusterName\"}"
    }
   ]
  },
  { "title": "Go Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory Statistics",
   "type": "graph",
   "description": "Heap, Stack and Total memory allocated to a Go process at the specified time.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{kubernetes_namespace=\"default\", cluster_name=~\"$ClusterName\"}",
     "legendFormat": "Total allocated memory in  {{kubernetes_pod_name}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{kubernetes_namespace=\"default\", cluster_name=~\"$ClusterName\"}",
     "legendFormat": "Stack memory in {{kubernetes_pod_name}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{kubernetes_namespace=\"default\", cluster_name=~\"$ClusterName\"}",
     "legendFormat": "Heap memory in {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{kubernetes_namespace=\"default\", cluster_name=~\"$ClusterName\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Process Memory In MiB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{kubernetes_namespace=\"default\", cluster_name=~\"$ClusterName\"}",
     "legendFormat": "Resident memory: {{kubernetes_pod_name}}"
    },
    {
     "expr": "process_virtual_memory_bytes{kubernetes_namespace=\"default\", cluster_name=~\"$ClusterName\"}",
     "legendFormat": "Virtual memory: {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Open File descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{kubernetes_namespace=\"default\", cluster_name=~\"$ClusterName\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{kubernetes_namespace=\"default\", cluster_name=~\"$ClusterName\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}