{
 "title": "Hyperledger Fabric",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(kube_pod_info,cluster_name)"
   }
  ]
 },
 "panels": [
  { "title": "Hyperledger Fabric Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fabric Version",
   "type": "singlestat",
   "description": "The active version of Fabric.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "fabric_version{cluster_name=~\"$ClusterName\"}"
    }
   ]
  },
  {
   "title": "Go Version",
   "type": "singlestat",
   "description": "The active version of Go.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "go_info{cluster_name=~\"$ClusterName\"}"
    }
   ]
  },
  {
   "title": "Ledger Block Height",
   "type": "singlestat",
   "description": "Height of the chain in blocks. ",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "ledger_blockchain_height{cluster_name=~\"$ClusterName\"}"
    }
   ]
  },
  {
   "title": "Ledger Transaction Count",
   "type": "singlestat",
   "description": "Number of transactions processed.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "ledger_transaction_count" }
   ]
  },
  {
   "title": "Endorsment Proposal Requests",
   "type": "singlestat",
   "description": "The number of proposals received.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "endorser_proposals_received{cluster_name=~\"$ClusterName\"}"
    }
   ]
  },
  {
   "title": "Endorsment Proposal Successful",
   "type": "singlestat",
   "description": "The number of successful proposals. ",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "endorser_successful_proposals{cluster_name=~\"$ClusterName\"}"
    }
   ]
  },
  {
   "title": "Couch DB Processing Time",
   "type": "graph",
   "description": "Time taken in seconds for the function to complete request to CouchDB.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(couchdb_processing_time_bucket{cluster_name=~\"$ClusterName\"}[5m])) by (le))",
     "legendFormat": "CouchDB"
    }
   ]
  },
  { "title": "Go Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Go Memory Allocations",
   "type": "graph",
   "description": "go_memstats_alloc_bytes",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{kubernetes_namespace=\"blockchain\", cluster_name=~\"$ClusterName\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Go Heap Objects",
   "type": "graph",
   "description": "go_memstats_alloc_bytes",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_heap_objects{job!=\"prometheus\",kubernetes_namespace=\"blockchain\", cluster_name=~\"$ClusterName\"}[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Go Garbage Collection",
   "type": "graph",
   "description": "go_gc_duration_seconds",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds{kubernetes_namespace=\"blockchain\", cluster_name=~\"$ClusterName\"}[5m])",
     "legendFormat": "{{app}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Go Free Memory",
   "type": "graph",
   "description": "go_gc_duration_seconds",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_frees_total{kubernetes_namespace=\"blockchain\", cluster_name=~\"$ClusterName\"}[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  { "title": "Ledger Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Ledger Block Processing Time",
   "type": "graph",
   "description": "Time taken in seconds for ledger block processing.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ledger_block_processing_time_bucket{cluster_name=~\"$ClusterName\"}[5m])) by (le))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "StateDB Commit Time",
   "type": "graph",
   "description": "Time taken in seconds for committing block changes to state db.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ledger_statedb_commit_time_bucket{cluster_name=~\"$ClusterName\"}[5m])) by (le))",
     "legendFormat": " "
    }
   ]
  },
  { "title": "Orderer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Orderer Broadcasts",
   "type": "table",
   "description": "The number of transactions processed.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "broadcast_processed_count{cluster_name=~\"$ClusterName\"}"
    }
   ]
  },
  { "title": "Chaincode Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Chaincode Shim Requests",
   "type": "graph",
   "description": "chaincode_shim_requests_received",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(chaincode_shim_requests_received[5m])",
     "legendFormat": "{{channel}}, {{Received}}, {{chaincode}}, {{type}}"
    },
    {
     "expr": "rate(chaincode_shim_requests_completed[5m])",
     "legendFormat": "{{channel}}, {{Completed}},  {{chaincode}}, {{type}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(chaincode_shim_request_duration_bucket{cluster_name=~\"$ClusterName\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Broadcast Enqueu",
   "type": "graph",
   "description": "broadcast_enqueue_duration_sum",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_frees_total{job!=\"prometheus\",kubernetes_namespace=\"blockchain\", cluster_name=~\"$ClusterName\"}[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "gRPC Closed Connections",
   "type": "graph",
   "description": "rate(grpc_comm_conn_closed[5m])",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_comm_conn_closed{kubernetes_namespace=\"blockchain\", cluster_name=~\"$ClusterName\"}[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Chaincode Launch Duration",
   "type": "graph",
   "description": "chaincode_shim_requests_received",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "chaincode_launch_duration_count{cluster_name=~\"$ClusterName\"}",
     "legendFormat": "{{Count}}, {{chaincode}}"
    },
    {
     "expr": "chaincode_launch_duration_sum{cluster_name=~\"$ClusterName\"}",
     "legendFormat": "{{Tota}}, {{chaincode}}"
    }
   ]
  }
 ]
}