// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth.proto

package auth

import (
	fmt "fmt"
	_ "github.com/datapace/datapace/proto/common"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthRequest struct {
	Token                string            `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Action               int64             `protobuf:"varint,2,opt,name=action,proto3" json:"action,omitempty"`
	Type                 string            `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Attributes           map[string]string `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{0}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthRequest) GetAction() int64 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *AuthRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AuthRequest) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type Token struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{1}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type UserEmail struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	ContactEmail         string   `protobuf:"bytes,2,opt,name=contactEmail,proto3" json:"contactEmail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserEmail) Reset()         { *m = UserEmail{} }
func (m *UserEmail) String() string { return proto.CompactTextString(m) }
func (*UserEmail) ProtoMessage()    {}
func (*UserEmail) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{2}
}

func (m *UserEmail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEmail.Unmarshal(m, b)
}
func (m *UserEmail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEmail.Marshal(b, m, deterministic)
}
func (m *UserEmail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEmail.Merge(m, src)
}
func (m *UserEmail) XXX_Size() int {
	return xxx_messageInfo_UserEmail.Size(m)
}
func (m *UserEmail) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEmail.DiscardUnknown(m)
}

var xxx_messageInfo_UserEmail proto.InternalMessageInfo

func (m *UserEmail) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserEmail) GetContactEmail() string {
	if m != nil {
		return m.ContactEmail
	}
	return ""
}

type User struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                *UserEmail `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName            string     `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string     `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Company              string     `protobuf:"bytes,5,opt,name=company,proto3" json:"company,omitempty"`
	Address              string     `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Phone                string     `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	Role                 string     `protobuf:"bytes,8,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{3}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() *UserEmail {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *User) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "datapace.AuthRequest")
	proto.RegisterMapType((map[string]string)(nil), "datapace.AuthRequest.AttributesEntry")
	proto.RegisterType((*Token)(nil), "datapace.Token")
	proto.RegisterType((*UserEmail)(nil), "datapace.UserEmail")
	proto.RegisterType((*User)(nil), "datapace.User")
}

func init() {
	proto.RegisterFile("proto/auth.proto", fileDescriptor_a9d38a2cdbb4f144)
}

var fileDescriptor_a9d38a2cdbb4f144 = []byte{
	// 489 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0x8d, 0xf3, 0xaf, 0xc9, 0xa4, 0x6a, 0xab, 0xf9, 0xfd, 0xa8, 0x2c, 0x03, 0x52, 0x64, 0x09,
	0x91, 0x82, 0x64, 0xa3, 0x70, 0x41, 0x48, 0x1c, 0x5a, 0xe1, 0x43, 0x2e, 0x1c, 0x0c, 0x5c, 0xb8,
	0x6d, 0xec, 0x4d, 0xb2, 0xaa, 0xed, 0x35, 0xf6, 0xb8, 0xc2, 0x7c, 0x4f, 0x0e, 0x7c, 0x18, 0x24,
	0xb4, 0xbb, 0x76, 0x9c, 0x84, 0xde, 0xde, 0x9b, 0xf7, 0x66, 0xe7, 0x8f, 0xc7, 0x70, 0x95, 0x17,
	0x92, 0xa4, 0xcf, 0x2a, 0xda, 0x79, 0x1a, 0xe2, 0x24, 0x66, 0xc4, 0x72, 0x16, 0x71, 0xe7, 0xe9,
	0x56, 0xca, 0x6d, 0xc2, 0x7d, 0x1d, 0x5f, 0x57, 0x1b, 0x9f, 0xa7, 0x39, 0xd5, 0xc6, 0xe6, 0xa0,
	0x49, 0x8c, 0x64, 0x9a, 0xca, 0xcc, 0xc4, 0xdc, 0x5f, 0x16, 0xcc, 0x6e, 0x2b, 0xda, 0x85, 0xfc,
	0x7b, 0xc5, 0x4b, 0xc2, 0xff, 0x61, 0x44, 0xf2, 0x9e, 0x67, 0xb6, 0x35, 0xb7, 0x16, 0xd3, 0xd0,
	0x10, 0xbc, 0x86, 0x31, 0x8b, 0x48, 0xc8, 0xcc, 0xee, 0xcf, 0xad, 0xc5, 0x20, 0x6c, 0x18, 0x22,
	0x0c, 0xa9, 0xce, 0xb9, 0x3d, 0xd0, 0x66, 0x8d, 0x31, 0x00, 0x60, 0x44, 0x85, 0x58, 0x57, 0xc4,
	0x4b, 0x7b, 0x38, 0x1f, 0x2c, 0x66, 0xcb, 0x17, 0x5e, 0xdb, 0xa1, 0x77, 0x50, 0xcc, 0xbb, 0xdd,
	0xfb, 0x82, 0x8c, 0x8a, 0x3a, 0x3c, 0x48, 0x74, 0x3e, 0xc0, 0xe5, 0x89, 0x8c, 0x57, 0x30, 0xb8,
	0xe7, 0x75, 0xd3, 0x99, 0x82, 0xaa, 0xdb, 0x07, 0x96, 0x54, 0x5c, 0xb7, 0x35, 0x0d, 0x0d, 0x79,
	0xdf, 0x7f, 0x67, 0xb9, 0xcf, 0x61, 0xf4, 0x45, 0xb7, 0xbe, 0xb7, 0x58, 0x07, 0x16, 0x37, 0x80,
	0xe9, 0xd7, 0x92, 0x17, 0x41, 0xca, 0x44, 0xa2, 0x2c, 0x5c, 0x81, 0xd6, 0xa2, 0x09, 0xba, 0x70,
	0x1e, 0xc9, 0x8c, 0x58, 0x44, 0xda, 0xd5, 0x94, 0x38, 0x8a, 0xb9, 0xbf, 0x2d, 0x18, 0xaa, 0x77,
	0xf0, 0x02, 0xfa, 0x22, 0x6e, 0xf2, 0xfb, 0x22, 0xc6, 0x9b, 0xf6, 0x49, 0x95, 0x35, 0x5b, 0xfe,
	0xd7, 0xcd, 0xbf, 0x2f, 0xdb, 0xd6, 0x79, 0x06, 0xd3, 0x8d, 0x28, 0x4a, 0xfa, 0xc4, 0xd2, 0x76,
	0x91, 0x5d, 0x00, 0x1d, 0x98, 0x24, 0xac, 0x11, 0x87, 0x5a, 0xdc, 0x73, 0xb4, 0xe1, 0x2c, 0x92,
	0x69, 0xce, 0xb2, 0xda, 0x1e, 0x69, 0xa9, 0xa5, 0x4a, 0x61, 0x71, 0x5c, 0xf0, 0xb2, 0xb4, 0xc7,
	0x46, 0x69, 0xa8, 0x9a, 0x35, 0xdf, 0xc9, 0x8c, 0xdb, 0x67, 0x66, 0x56, 0x4d, 0xd4, 0x77, 0x2c,
	0x64, 0xc2, 0xed, 0x89, 0xf9, 0x8e, 0x0a, 0x2f, 0xff, 0x34, 0x97, 0xf1, 0x99, 0x17, 0x0f, 0x22,
	0xe2, 0xf8, 0x1a, 0x26, 0xab, 0x98, 0x67, 0x24, 0x36, 0x35, 0x5e, 0x76, 0xf3, 0xe8, 0x2d, 0x3b,
	0xe7, 0x5d, 0x60, 0xf5, 0xd1, 0xed, 0xa1, 0x0f, 0x23, 0xb3, 0xdb, 0x7f, 0x9c, 0x8f, 0xad, 0xc2,
	0xed, 0xe1, 0x2b, 0x98, 0x28, 0x7a, 0x57, 0xaf, 0x62, 0x3c, 0x7a, 0xcc, 0xb9, 0x38, 0x4e, 0x70,
	0x7b, 0xf8, 0x06, 0xc6, 0xc1, 0x0f, 0x51, 0x52, 0x79, 0xe2, 0xbc, 0xf6, 0xcc, 0xf5, 0x7b, 0xed,
	0xf5, 0x7b, 0x81, 0xba, 0x7e, 0xb7, 0x87, 0x4b, 0x98, 0xaa, 0x51, 0x64, 0x21, 0x7e, 0x72, 0x7c,
	0xf2, 0xe8, 0x31, 0x9e, 0x8e, 0x70, 0x77, 0xf3, 0xed, 0xe5, 0x56, 0xd0, 0xae, 0x5a, 0x7b, 0x91,
	0x4c, 0xfd, 0x56, 0xeb, 0x40, 0xf7, 0x17, 0xae, 0xc7, 0x1a, 0xbf, 0xfd, 0x1b, 0x00, 0x00, 0xff,
	0xff, 0xf2, 0x13, 0xd6, 0xc1, 0x9a, 0x03, 0x00, 0x00,
}
