image: golang

variables:
  USER: "darko.draskovic"
  PASS: "2miLLi4on"

stages:
    # - build
    - develop
    # - deploy    
    
install_and_test:
  stage: develop
  script:
    - apt-get update
    - apt-get install -y git
    - cd /go/src/
    - git clone https://$USER:$PASS@gitlab.com/drasko/monetasa
    - cd /go/src/monetasa/auth
    - go test
    - cd /go/src/monetasa/dapp
    - go test
