image: golang

stages:
    # - build
    - develop
    # - deploy

install_and_test:
  stage: develop
  script:
    - cd /go/src/
    - git clone $CI_REPOSITORY_URL
    - cd /go/src/monetasa/auth
    - go test
    - cd /go/src/monetasa/dapp
    - go test
