image: gitlab/dind

variables:
  DOCKER_DRIVER: overlay2

stages:
    - develop

install_and_test:
  stage: develop
  script:
    - apt-get update
    - wget -q https://dl.google.com/go/go1.10.linux-amd64.tar.gz
    - tar -zxf go1.10.linux-amd64.tar.gz
    - mv go /usr/local
    - export GOROOT=/usr/local/go
    - export GOPATH=/go
    - export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
    - apt-get -y install git make libltdl-dev unzip
    - PROTOC_ZIP=protoc-3.5.1-linux-x86_64.zip
    - curl -0L https://github.com/google/protobuf/releases/download/v3.5.1/$PROTOC_ZIP -o $PROTOC_ZIP
    - mkdir protoc3
    - unzip -o $PROTOC_ZIP -d protoc3
    - mv protoc3/bin/* /usr/local/bin/
    - mv protoc3/include/* /usr/local/include/
    - rm -r protoc3
    - rm -f $PROTOC_ZIP
    - export PATH=$PATH:/usr/local/bin/protoc
    - go get -u github.com/golang/protobuf/protoc-gen-go
    - go get -u google.golang.org/grpc
    - mkdir -p $GOPATH/src/monetasa
    - mv * $GOPATH/src/monetasa
    - cd $GOPATH/src/monetasa
    - make proto
    - go test ./... -race
