// Code generated by protoc-gen-go. DO NOT EDIT.
// source: executions.proto

package datapace

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Algorithm struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Algorithm) Reset()         { *m = Algorithm{} }
func (m *Algorithm) String() string { return proto.CompactTextString(m) }
func (*Algorithm) ProtoMessage()    {}
func (*Algorithm) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef99ea0b3f4241db, []int{0}
}

func (m *Algorithm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Algorithm.Unmarshal(m, b)
}
func (m *Algorithm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Algorithm.Marshal(b, m, deterministic)
}
func (m *Algorithm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Algorithm.Merge(m, src)
}
func (m *Algorithm) XXX_Size() int {
	return xxx_messageInfo_Algorithm.Size(m)
}
func (m *Algorithm) XXX_DiscardUnknown() {
	xxx_messageInfo_Algorithm.DiscardUnknown(m)
}

var xxx_messageInfo_Algorithm proto.InternalMessageInfo

func (m *Algorithm) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Algorithm) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Algorithm) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Dataset struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Dataset) Reset()         { *m = Dataset{} }
func (m *Dataset) String() string { return proto.CompactTextString(m) }
func (*Dataset) ProtoMessage()    {}
func (*Dataset) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef99ea0b3f4241db, []int{1}
}

func (m *Dataset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dataset.Unmarshal(m, b)
}
func (m *Dataset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dataset.Marshal(b, m, deterministic)
}
func (m *Dataset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dataset.Merge(m, src)
}
func (m *Dataset) XXX_Size() int {
	return xxx_messageInfo_Dataset.Size(m)
}
func (m *Dataset) XXX_DiscardUnknown() {
	xxx_messageInfo_Dataset.DiscardUnknown(m)
}

var xxx_messageInfo_Dataset proto.InternalMessageInfo

func (m *Dataset) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Dataset) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterType((*Algorithm)(nil), "datapace.Algorithm")
	proto.RegisterMapType((map[string]string)(nil), "datapace.Algorithm.MetadataEntry")
	proto.RegisterType((*Dataset)(nil), "datapace.Dataset")
	proto.RegisterMapType((map[string]string)(nil), "datapace.Dataset.MetadataEntry")
}

func init() { proto.RegisterFile("executions.proto", fileDescriptor_ef99ea0b3f4241db) }

var fileDescriptor_ef99ea0b3f4241db = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xad, 0x48, 0x4d,
	0x2e, 0x2d, 0xc9, 0xcc, 0xcf, 0x2b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0x49,
	0x2c, 0x49, 0x2c, 0x48, 0x4c, 0x4e, 0x95, 0x92, 0x4e, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07,
	0x8b, 0x27, 0x95, 0xa6, 0xe9, 0xa7, 0xe6, 0x16, 0x94, 0x54, 0x42, 0x94, 0x29, 0xad, 0x66, 0xe4,
	0xe2, 0x74, 0xcc, 0x49, 0xcf, 0x2f, 0xca, 0x2c, 0xc9, 0xc8, 0x15, 0xe2, 0xe3, 0x62, 0xca, 0x4c,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xca, 0x4c, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b,
	0xcc, 0x4d, 0x95, 0x60, 0x02, 0x8b, 0x80, 0xd9, 0x42, 0xb6, 0x5c, 0x1c, 0xb9, 0xa9, 0x25, 0x89,
	0x20, 0xe3, 0x25, 0x98, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0x14, 0xf5, 0x60, 0x76, 0xe9, 0xc1, 0x8d,
	0xd2, 0xf3, 0x85, 0xaa, 0x71, 0xcd, 0x2b, 0x29, 0xaa, 0x0c, 0x82, 0x6b, 0x91, 0xb2, 0xe6, 0xe2,
	0x45, 0x91, 0x12, 0x12, 0xe0, 0x62, 0xce, 0x4e, 0xad, 0x84, 0x5a, 0x0a, 0x62, 0x0a, 0x89, 0x70,
	0xb1, 0x96, 0x25, 0xe6, 0x94, 0xc2, 0xac, 0x85, 0x70, 0xac, 0x98, 0x2c, 0x18, 0x95, 0x26, 0x33,
	0x72, 0xb1, 0xbb, 0x24, 0x96, 0x24, 0x16, 0xa7, 0x96, 0x60, 0xb8, 0xd5, 0x1a, 0xc9, 0x5d, 0x4c,
	0x60, 0x77, 0xc9, 0x23, 0xdc, 0x05, 0xd5, 0x44, 0x13, 0x57, 0x19, 0x4d, 0x66, 0xe4, 0x12, 0x74,
	0x85, 0x87, 0x7f, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x03, 0x17, 0xbf, 0x73, 0x51,
	0x6a, 0x62, 0x49, 0x2a, 0x22, 0x78, 0x85, 0xb1, 0x04, 0x94, 0x94, 0x98, 0x1e, 0x24, 0x7e, 0xf4,
	0x60, 0xf1, 0xa3, 0xe7, 0x0a, 0x8a, 0x1f, 0x25, 0x06, 0x21, 0x1b, 0x2e, 0x5e, 0x88, 0x09, 0x30,
	0x2f, 0x0b, 0x62, 0x78, 0x08, 0xb7, 0xee, 0x24, 0x36, 0xb0, 0x88, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0x42, 0xe2, 0x4a, 0x60, 0x1b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExecutionsServiceClient is the client API for ExecutionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExecutionsServiceClient interface {
	CreateAlgorithm(ctx context.Context, in *Algorithm, opts ...grpc.CallOption) (*empty.Empty, error)
	CreateDataset(ctx context.Context, in *Dataset, opts ...grpc.CallOption) (*empty.Empty, error)
}

type executionsServiceClient struct {
	cc *grpc.ClientConn
}

func NewExecutionsServiceClient(cc *grpc.ClientConn) ExecutionsServiceClient {
	return &executionsServiceClient{cc}
}

func (c *executionsServiceClient) CreateAlgorithm(ctx context.Context, in *Algorithm, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/datapace.ExecutionsService/CreateAlgorithm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionsServiceClient) CreateDataset(ctx context.Context, in *Dataset, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/datapace.ExecutionsService/CreateDataset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecutionsServiceServer is the server API for ExecutionsService service.
type ExecutionsServiceServer interface {
	CreateAlgorithm(context.Context, *Algorithm) (*empty.Empty, error)
	CreateDataset(context.Context, *Dataset) (*empty.Empty, error)
}

// UnimplementedExecutionsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedExecutionsServiceServer struct {
}

func (*UnimplementedExecutionsServiceServer) CreateAlgorithm(ctx context.Context, req *Algorithm) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAlgorithm not implemented")
}
func (*UnimplementedExecutionsServiceServer) CreateDataset(ctx context.Context, req *Dataset) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDataset not implemented")
}

func RegisterExecutionsServiceServer(s *grpc.Server, srv ExecutionsServiceServer) {
	s.RegisterService(&_ExecutionsService_serviceDesc, srv)
}

func _ExecutionsService_CreateAlgorithm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Algorithm)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionsServiceServer).CreateAlgorithm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datapace.ExecutionsService/CreateAlgorithm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionsServiceServer).CreateAlgorithm(ctx, req.(*Algorithm))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionsService_CreateDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Dataset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionsServiceServer).CreateDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datapace.ExecutionsService/CreateDataset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionsServiceServer).CreateDataset(ctx, req.(*Dataset))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExecutionsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "datapace.ExecutionsService",
	HandlerType: (*ExecutionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAlgorithm",
			Handler:    _ExecutionsService_CreateAlgorithm_Handler,
		},
		{
			MethodName: "CreateDataset",
			Handler:    _ExecutionsService_CreateDataset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "executions.proto",
}
