[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "9.0.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "v1.4.0"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.6.0"

[[constraint]]
  name = "github.com/go-zoo/bone"
  version = "1.2.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.4.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[[override]]
  name = "github.com/spf13/viper"
  branch = "master"
  
[[constraint]]
  name = "github.com/hyperledger/fabric-sdk-go"
  version = "=v1.0.0-alpha5"

[[constraint]]
  name = "github.com/hyperledger/fabric"
  version = "=v1.4.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/ory/dockertest"
  version = "3.1.6"

[[constraint]]
  name = "cloud.google.com/go"
  version = "0.27.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/jmoiron/sqlx"
  version = "1.2.0"

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.3.0"

[[constraint]]
  name = "github.com/rubenv/sql-migrate"
  revision = "64f95ea68aa39b024c83a7d0d60910dbdafcfb04"
