[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "9.0.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.6.0"

[[constraint]]
  name = "github.com/go-zoo/bone"
  version = "1.2.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[[override]]
  name = "google.golang.org/grpc"
  version = "1.12.0"

[[override]]
  name = "github.com/golang/protobuf"
  branch = "master"

[[override]]
  name = "github.com/pkg/errors"
  branch = "master"

[[override]]
  name = "github.com/spf13/viper"
  branch = "master"

[[override]]
  name = "github.com/docker/docker"
  branch = "master"

[[override]]
  name = "github.com/docker/libnetwork"
  branch = "master"

[[override]]
  name = "github.com/hyperledger/fabric-amcl"
  revision = "31cc24e414990009f09ab4d4d9a85eb94d17ac31"

[[constraint]]
  name = "github.com/hyperledger/fabric-sdk-go"
  version = "=v1.0.0-alpha4"

[[constraint]]
  name = "github.com/hyperledger/fabric"
  version = "=v1.2.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/ory/dockertest"
  version = "3.1.6"

[[constraint]]
  name = "cloud.google.com/go"
  version = "0.27.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"
