// Code generated by protoc-gen-go. DO NOT EDIT.
// source: streams.proto

package monetasa

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Stream struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Owner                string   `protobuf:"bytes,3,opt,name=owner" json:"owner,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=url" json:"url,omitempty"`
	Price                uint64   `protobuf:"varint,5,opt,name=price" json:"price,omitempty"`
	Bq                   bool     `protobuf:"varint,6,opt,name=bq" json:"bq,omitempty"`
	Project              string   `protobuf:"bytes,7,opt,name=project" json:"project,omitempty"`
	Dataset              string   `protobuf:"bytes,8,opt,name=dataset" json:"dataset,omitempty"`
	Table                string   `protobuf:"bytes,9,opt,name=table" json:"table,omitempty"`
	Fields               string   `protobuf:"bytes,10,opt,name=fields" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stream) Reset()         { *m = Stream{} }
func (m *Stream) String() string { return proto.CompactTextString(m) }
func (*Stream) ProtoMessage()    {}
func (*Stream) Descriptor() ([]byte, []int) {
	return fileDescriptor_streams_5616dc4532f0af52, []int{0}
}
func (m *Stream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stream.Unmarshal(m, b)
}
func (m *Stream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stream.Marshal(b, m, deterministic)
}
func (dst *Stream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stream.Merge(dst, src)
}
func (m *Stream) XXX_Size() int {
	return xxx_messageInfo_Stream.Size(m)
}
func (m *Stream) XXX_DiscardUnknown() {
	xxx_messageInfo_Stream.DiscardUnknown(m)
}

var xxx_messageInfo_Stream proto.InternalMessageInfo

func (m *Stream) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Stream) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Stream) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Stream) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Stream) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Stream) GetBq() bool {
	if m != nil {
		return m.Bq
	}
	return false
}

func (m *Stream) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *Stream) GetDataset() string {
	if m != nil {
		return m.Dataset
	}
	return ""
}

func (m *Stream) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *Stream) GetFields() string {
	if m != nil {
		return m.Fields
	}
	return ""
}

func init() {
	proto.RegisterType((*Stream)(nil), "monetasa.Stream")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StreamsServiceClient is the client API for StreamsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StreamsServiceClient interface {
	One(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Stream, error)
}

type streamsServiceClient struct {
	cc *grpc.ClientConn
}

func NewStreamsServiceClient(cc *grpc.ClientConn) StreamsServiceClient {
	return &streamsServiceClient{cc}
}

func (c *streamsServiceClient) One(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Stream, error) {
	out := new(Stream)
	err := c.cc.Invoke(ctx, "/monetasa.StreamsService/One", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamsServiceServer is the server API for StreamsService service.
type StreamsServiceServer interface {
	One(context.Context, *ID) (*Stream, error)
}

func RegisterStreamsServiceServer(s *grpc.Server, srv StreamsServiceServer) {
	s.RegisterService(&_StreamsService_serviceDesc, srv)
}

func _StreamsService_One_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServiceServer).One(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monetasa.StreamsService/One",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServiceServer).One(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

var _StreamsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "monetasa.StreamsService",
	HandlerType: (*StreamsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "One",
			Handler:    _StreamsService_One_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "streams.proto",
}

func init() { proto.RegisterFile("streams.proto", fileDescriptor_streams_5616dc4532f0af52) }

var fileDescriptor_streams_5616dc4532f0af52 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x71, 0x92, 0xa6, 0xe9, 0xa9, 0x54, 0x95, 0x85, 0xd0, 0xa9, 0x53, 0xd4, 0x85, 0x4c,
	0x19, 0x60, 0x62, 0x67, 0x61, 0x42, 0x4a, 0x9f, 0xc0, 0x49, 0x0e, 0x29, 0x28, 0xb6, 0x53, 0xdb,
	0xc0, 0xcb, 0xf2, 0x30, 0xc8, 0xe7, 0x56, 0xdd, 0xee, 0xfb, 0xee, 0xb7, 0x7d, 0x3e, 0xb8, 0xf7,
	0xc1, 0x91, 0xd2, 0xbe, 0x5d, 0x9c, 0x0d, 0x56, 0x56, 0xda, 0x1a, 0x0a, 0xca, 0xab, 0xc3, 0x76,
	0xb0, 0x5a, 0x5b, 0x93, 0xfc, 0xf1, 0x4f, 0x40, 0x79, 0xe2, 0xa4, 0xdc, 0x41, 0x36, 0x8d, 0x28,
	0x6a, 0xd1, 0x6c, 0xba, 0x6c, 0x1a, 0xa5, 0x84, 0xc2, 0x28, 0x4d, 0x98, 0xb1, 0xe1, 0x5a, 0x3e,
	0xc0, 0xca, 0xfe, 0x1a, 0x72, 0x98, 0xb3, 0x4c, 0x20, 0xf7, 0x90, 0x7f, 0xbb, 0x19, 0x0b, 0x76,
	0xb1, 0x8c, 0xb9, 0xc5, 0x4d, 0x03, 0xe1, 0xaa, 0x16, 0x4d, 0xd1, 0x25, 0x88, 0x2f, 0xf4, 0x67,
	0x2c, 0x6b, 0xd1, 0x54, 0x5d, 0xd6, 0x9f, 0x25, 0xc2, 0x7a, 0x71, 0xf6, 0x8b, 0x86, 0x80, 0x6b,
	0x3e, 0x7b, 0xc5, 0xd8, 0x19, 0x55, 0x50, 0x9e, 0x02, 0x56, 0xa9, 0x73, 0xc1, 0x78, 0x73, 0x50,
	0xfd, 0x4c, 0xb8, 0x49, 0x13, 0x30, 0xc8, 0x47, 0x28, 0x3f, 0x27, 0x9a, 0x47, 0x8f, 0xc0, 0xfa,
	0x42, 0xcf, 0xaf, 0xb0, 0x4b, 0xbf, 0xf3, 0x27, 0x72, 0x3f, 0x71, 0x86, 0x27, 0xc8, 0x3f, 0x0c,
	0xc9, 0x6d, 0x7b, 0x5d, 0x48, 0xfb, 0xfe, 0x76, 0xd8, 0xdf, 0x28, 0xc5, 0x8f, 0x77, 0x7d, 0xc9,
	0x0b, 0x7a, 0xf9, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xeb, 0xf8, 0xb7, 0x8a, 0x49, 0x01, 0x00, 0x00,
}
