// Code generated by protoc-gen-go. DO NOT EDIT.
// source: streams.proto

package datapace

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Stream struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Owner                string   `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Price                uint64   `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	External             bool     `protobuf:"varint,6,opt,name=external,proto3" json:"external,omitempty"`
	Project              string   `protobuf:"bytes,7,opt,name=project,proto3" json:"project,omitempty"`
	Dataset              string   `protobuf:"bytes,8,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Table                string   `protobuf:"bytes,9,opt,name=table,proto3" json:"table,omitempty"`
	Fields               string   `protobuf:"bytes,10,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stream) Reset()         { *m = Stream{} }
func (m *Stream) String() string { return proto.CompactTextString(m) }
func (*Stream) ProtoMessage()    {}
func (*Stream) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{0}
}

func (m *Stream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stream.Unmarshal(m, b)
}
func (m *Stream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stream.Marshal(b, m, deterministic)
}
func (m *Stream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stream.Merge(m, src)
}
func (m *Stream) XXX_Size() int {
	return xxx_messageInfo_Stream.Size(m)
}
func (m *Stream) XXX_DiscardUnknown() {
	xxx_messageInfo_Stream.DiscardUnknown(m)
}

var xxx_messageInfo_Stream proto.InternalMessageInfo

func (m *Stream) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Stream) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Stream) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Stream) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Stream) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Stream) GetExternal() bool {
	if m != nil {
		return m.External
	}
	return false
}

func (m *Stream) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *Stream) GetDataset() string {
	if m != nil {
		return m.Dataset
	}
	return ""
}

func (m *Stream) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *Stream) GetFields() string {
	if m != nil {
		return m.Fields
	}
	return ""
}

func init() {
	proto.RegisterType((*Stream)(nil), "datapace.Stream")
}

func init() { proto.RegisterFile("streams.proto", fileDescriptor_c6bbf8af0ec331d6) }

var fileDescriptor_c6bbf8af0ec331d6 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x86, 0xc9, 0x47, 0xd3, 0xf4, 0x54, 0xaa, 0xea, 0x84, 0xd0, 0x29, 0x53, 0xd4, 0x85, 0x4c,
	0x19, 0x60, 0x62, 0x67, 0x61, 0x42, 0x4a, 0x7f, 0x81, 0x9b, 0x1c, 0x52, 0x50, 0x62, 0x47, 0xb6,
	0xf9, 0xf8, 0xc9, 0xfc, 0x0c, 0xe4, 0x73, 0x4b, 0xb7, 0x7b, 0x9e, 0x7b, 0x95, 0xbc, 0x3e, 0xb8,
	0x75, 0xde, 0xb2, 0x9a, 0x5d, 0xbb, 0x58, 0xe3, 0x0d, 0x96, 0x83, 0xf2, 0x6a, 0x51, 0x3d, 0x57,
	0xdb, 0xde, 0xcc, 0xb3, 0xd1, 0xd1, 0x1f, 0x7e, 0x13, 0x28, 0x8e, 0x92, 0xc4, 0x1d, 0xa4, 0xe3,
	0x40, 0x49, 0x9d, 0x34, 0x9b, 0x2e, 0x1d, 0x07, 0x44, 0xc8, 0xb5, 0x9a, 0x99, 0x52, 0x31, 0x32,
	0xe3, 0x1d, 0xac, 0xcc, 0xb7, 0x66, 0x4b, 0x99, 0xc8, 0x08, 0xb8, 0x87, 0xec, 0xd3, 0x4e, 0x94,
	0x8b, 0x0b, 0x63, 0xc8, 0x2d, 0x76, 0xec, 0x99, 0x56, 0x75, 0xd2, 0xe4, 0x5d, 0x04, 0xac, 0xa0,
	0xe4, 0x1f, 0xcf, 0x56, 0xab, 0x89, 0x8a, 0x3a, 0x69, 0xca, 0xee, 0x9f, 0x91, 0x60, 0xbd, 0x58,
	0xf3, 0xc1, 0xbd, 0xa7, 0xb5, 0x7c, 0xe7, 0x82, 0x61, 0x13, 0xca, 0x3b, 0xf6, 0x54, 0xc6, 0xcd,
	0x19, 0xc3, 0x5f, 0xbc, 0x3a, 0x4d, 0x4c, 0x9b, 0xd8, 0x46, 0x00, 0xef, 0xa1, 0x78, 0x1f, 0x79,
	0x1a, 0x1c, 0x81, 0xe8, 0x33, 0x3d, 0x3e, 0xc3, 0x2e, 0xbe, 0xd4, 0x1d, 0xd9, 0x7e, 0x85, 0x3e,
	0x0f, 0x90, 0xbd, 0x69, 0xc6, 0x6d, 0x7b, 0x39, 0x4e, 0xfb, 0xfa, 0x52, 0xed, 0xaf, 0x14, 0xe3,
	0x87, 0x9b, 0x53, 0x21, 0xc7, 0x7a, 0xfa, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x3b, 0x25, 0xf9,
	0x55, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StreamsServiceClient is the client API for StreamsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StreamsServiceClient interface {
	One(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Stream, error)
}

type streamsServiceClient struct {
	cc *grpc.ClientConn
}

func NewStreamsServiceClient(cc *grpc.ClientConn) StreamsServiceClient {
	return &streamsServiceClient{cc}
}

func (c *streamsServiceClient) One(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Stream, error) {
	out := new(Stream)
	err := c.cc.Invoke(ctx, "/datapace.StreamsService/One", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamsServiceServer is the server API for StreamsService service.
type StreamsServiceServer interface {
	One(context.Context, *ID) (*Stream, error)
}

// UnimplementedStreamsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStreamsServiceServer struct {
}

func (*UnimplementedStreamsServiceServer) One(ctx context.Context, req *ID) (*Stream, error) {
	return nil, status.Errorf(codes.Unimplemented, "method One not implemented")
}

func RegisterStreamsServiceServer(s *grpc.Server, srv StreamsServiceServer) {
	s.RegisterService(&_StreamsService_serviceDesc, srv)
}

func _StreamsService_One_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServiceServer).One(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datapace.StreamsService/One",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServiceServer).One(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

var _StreamsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "datapace.StreamsService",
	HandlerType: (*StreamsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "One",
			Handler:    _StreamsService_One_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "streams.proto",
}
