// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transactions.proto

package monetasa

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TransferData struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Value                uint64   `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferData) Reset()         { *m = TransferData{} }
func (m *TransferData) String() string { return proto.CompactTextString(m) }
func (*TransferData) ProtoMessage()    {}
func (*TransferData) Descriptor() ([]byte, []int) {
	return fileDescriptor_transactions_f40bfb007e2dbf2a, []int{0}
}
func (m *TransferData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferData.Unmarshal(m, b)
}
func (m *TransferData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferData.Marshal(b, m, deterministic)
}
func (dst *TransferData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferData.Merge(dst, src)
}
func (m *TransferData) XXX_Size() int {
	return xxx_messageInfo_TransferData.Size(m)
}
func (m *TransferData) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferData.DiscardUnknown(m)
}

var xxx_messageInfo_TransferData proto.InternalMessageInfo

func (m *TransferData) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *TransferData) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *TransferData) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*TransferData)(nil), "monetasa.TransferData")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransactionsServiceClient is the client API for TransactionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransactionsServiceClient interface {
	CreateUser(ctx context.Context, in *ID, opts ...grpc.CallOption) (*empty.Empty, error)
	Transfer(ctx context.Context, in *TransferData, opts ...grpc.CallOption) (*empty.Empty, error)
}

type transactionsServiceClient struct {
	cc *grpc.ClientConn
}

func NewTransactionsServiceClient(cc *grpc.ClientConn) TransactionsServiceClient {
	return &transactionsServiceClient{cc}
}

func (c *transactionsServiceClient) CreateUser(ctx context.Context, in *ID, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/monetasa.TransactionsService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionsServiceClient) Transfer(ctx context.Context, in *TransferData, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/monetasa.TransactionsService/Transfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionsServiceServer is the server API for TransactionsService service.
type TransactionsServiceServer interface {
	CreateUser(context.Context, *ID) (*empty.Empty, error)
	Transfer(context.Context, *TransferData) (*empty.Empty, error)
}

func RegisterTransactionsServiceServer(s *grpc.Server, srv TransactionsServiceServer) {
	s.RegisterService(&_TransactionsService_serviceDesc, srv)
}

func _TransactionsService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionsServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monetasa.TransactionsService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionsServiceServer).CreateUser(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionsService_Transfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionsServiceServer).Transfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monetasa.TransactionsService/Transfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionsServiceServer).Transfer(ctx, req.(*TransferData))
	}
	return interceptor(ctx, in, info, handler)
}

var _TransactionsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "monetasa.TransactionsService",
	HandlerType: (*TransactionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _TransactionsService_CreateUser_Handler,
		},
		{
			MethodName: "Transfer",
			Handler:    _TransactionsService_Transfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transactions.proto",
}

func init() { proto.RegisterFile("transactions.proto", fileDescriptor_transactions_f40bfb007e2dbf2a) }

var fileDescriptor_transactions_f40bfb007e2dbf2a = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0xce, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x06, 0x60, 0x37, 0x56, 0xa9, 0x43, 0xf0, 0x30, 0x4a, 0x09, 0xf1, 0x52, 0x7a, 0xea, 0x69,
	0x0b, 0xea, 0xd1, 0x9b, 0x15, 0xf4, 0x5a, 0xeb, 0x03, 0x4c, 0xc3, 0xa4, 0x14, 0xba, 0x3b, 0x65,
	0x77, 0x1a, 0xf0, 0x11, 0x7c, 0x6b, 0xc9, 0x2e, 0xc1, 0x5c, 0xbc, 0xed, 0xff, 0xb3, 0xff, 0xf0,
	0x01, 0x6a, 0x20, 0x1f, 0xa9, 0xd1, 0x83, 0xf8, 0x68, 0x4f, 0x41, 0x54, 0x70, 0xea, 0xc4, 0xb3,
	0x52, 0xa4, 0xfa, 0x61, 0x2f, 0xb2, 0x3f, 0xf2, 0x2a, 0xf5, 0xbb, 0x73, 0xbb, 0x62, 0x77, 0xd2,
	0xef, 0xfc, 0xad, 0x2e, 0x1b, 0x71, 0x4e, 0x7c, 0x4e, 0x8b, 0x77, 0x28, 0xb7, 0xfd, 0xa9, 0x96,
	0xc3, 0x9a, 0x94, 0x10, 0x61, 0xd2, 0x06, 0x71, 0x95, 0x99, 0x9b, 0xe5, 0xcd, 0x26, 0xbd, 0xf1,
	0x16, 0x0a, 0x95, 0xaa, 0x48, 0x4d, 0xa1, 0x82, 0xf7, 0x70, 0xd5, 0xd1, 0xf1, 0xcc, 0xd5, 0xe5,
	0xdc, 0x2c, 0x27, 0x9b, 0x1c, 0x1e, 0x7f, 0x0c, 0xdc, 0x6d, 0x47, 0xaa, 0x4f, 0x0e, 0xdd, 0xa1,
	0x61, 0x7c, 0x06, 0x78, 0x0d, 0x4c, 0xca, 0x5f, 0x91, 0x03, 0x96, 0x76, 0x50, 0xda, 0x8f, 0x75,
	0x3d, 0xb3, 0x59, 0x6a, 0x07, 0xa9, 0x7d, 0xeb, 0xa5, 0x8b, 0x0b, 0x7c, 0x81, 0xe9, 0xe0, 0xc2,
	0xd9, 0xdf, 0x66, 0x6c, 0xfd, 0x7f, 0xbd, 0xbb, 0x4e, 0xcd, 0xd3, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x53, 0xd4, 0x4c, 0xd7, 0x27, 0x01, 0x00, 0x00,
}
