// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transactions.proto

package datapace

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransferData struct {
	StreamID             string   `protobuf:"bytes,1,opt,name=streamID,proto3" json:"streamID,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Value                uint64   `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferData) Reset()         { *m = TransferData{} }
func (m *TransferData) String() string { return proto.CompactTextString(m) }
func (*TransferData) ProtoMessage()    {}
func (*TransferData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b72849cf10e9c77, []int{0}
}

func (m *TransferData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferData.Unmarshal(m, b)
}
func (m *TransferData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferData.Marshal(b, m, deterministic)
}
func (m *TransferData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferData.Merge(m, src)
}
func (m *TransferData) XXX_Size() int {
	return xxx_messageInfo_TransferData.Size(m)
}
func (m *TransferData) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferData.DiscardUnknown(m)
}

var xxx_messageInfo_TransferData proto.InternalMessageInfo

func (m *TransferData) GetStreamID() string {
	if m != nil {
		return m.StreamID
	}
	return ""
}

func (m *TransferData) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *TransferData) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *TransferData) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*TransferData)(nil), "datapace.TransferData")
}

func init() { proto.RegisterFile("transactions.proto", fileDescriptor_0b72849cf10e9c77) }

var fileDescriptor_0b72849cf10e9c77 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x4d, 0x8c, 0x12, 0x87, 0xe0, 0x61, 0x94, 0x12, 0xe2, 0xa5, 0xf4, 0xd4, 0xd3, 0x16,
	0xd4, 0xa3, 0x37, 0xe3, 0xa1, 0xd7, 0x5a, 0x1f, 0x60, 0x9a, 0x4e, 0x4a, 0xa1, 0x9b, 0x09, 0x93,
	0x69, 0xc1, 0x47, 0xf0, 0xad, 0xa5, 0x1b, 0xa2, 0xb9, 0xf4, 0xb6, 0xff, 0xc7, 0xfe, 0xc3, 0xff,
	0x01, 0x9a, 0x52, 0xd3, 0x51, 0x65, 0x7b, 0x69, 0x3a, 0xd7, 0xaa, 0x98, 0x60, 0xba, 0x25, 0xa3,
	0x96, 0x2a, 0x2e, 0x9e, 0x76, 0x22, 0xbb, 0x03, 0x2f, 0x02, 0xdf, 0x1c, 0xeb, 0x05, 0xfb, 0xd6,
	0xbe, 0xfb, 0x6f, 0x45, 0x56, 0x89, 0xf7, 0xd2, 0xf4, 0x69, 0xb6, 0x85, 0x6c, 0x7d, 0x3e, 0x55,
	0xb3, 0x96, 0x64, 0x84, 0x05, 0xa4, 0x9d, 0x29, 0x93, 0x5f, 0x96, 0x79, 0x34, 0x8d, 0xe6, 0x77,
	0xab, 0xbf, 0x8c, 0x08, 0x49, 0xad, 0xe2, 0xf3, 0x38, 0xf0, 0xf0, 0xc6, 0x7b, 0x88, 0x4d, 0xf2,
	0xeb, 0x40, 0x62, 0x13, 0x7c, 0x84, 0x9b, 0x13, 0x1d, 0x8e, 0x9c, 0x27, 0xd3, 0x68, 0x9e, 0xac,
	0xfa, 0xf0, 0xfc, 0x13, 0xc1, 0xc3, 0x7a, 0xb4, 0xf8, 0x93, 0xf5, 0xb4, 0xaf, 0x18, 0x5f, 0x01,
	0xde, 0x95, 0xc9, 0xf8, 0xab, 0x63, 0xc5, 0xcc, 0x0d, 0x06, 0x6e, 0x59, 0x16, 0x13, 0xd7, 0x5b,
	0xb8, 0xc1, 0xc2, 0x7d, 0x9c, 0x2d, 0x66, 0x57, 0xf8, 0x06, 0xe9, 0xb0, 0x19, 0x27, 0xff, 0x9d,
	0xb1, 0xc7, 0xe5, 0xf6, 0xe6, 0x36, 0x90, 0x97, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x66, 0x38,
	0x4a, 0x05, 0x43, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransactionsServiceClient is the client API for TransactionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransactionsServiceClient interface {
	CreateUser(ctx context.Context, in *ID, opts ...grpc.CallOption) (*empty.Empty, error)
	Transfer(ctx context.Context, in *TransferData, opts ...grpc.CallOption) (*empty.Empty, error)
}

type transactionsServiceClient struct {
	cc *grpc.ClientConn
}

func NewTransactionsServiceClient(cc *grpc.ClientConn) TransactionsServiceClient {
	return &transactionsServiceClient{cc}
}

func (c *transactionsServiceClient) CreateUser(ctx context.Context, in *ID, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/datapace.TransactionsService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionsServiceClient) Transfer(ctx context.Context, in *TransferData, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/datapace.TransactionsService/Transfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionsServiceServer is the server API for TransactionsService service.
type TransactionsServiceServer interface {
	CreateUser(context.Context, *ID) (*empty.Empty, error)
	Transfer(context.Context, *TransferData) (*empty.Empty, error)
}

func RegisterTransactionsServiceServer(s *grpc.Server, srv TransactionsServiceServer) {
	s.RegisterService(&_TransactionsService_serviceDesc, srv)
}

func _TransactionsService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionsServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datapace.TransactionsService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionsServiceServer).CreateUser(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionsService_Transfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionsServiceServer).Transfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datapace.TransactionsService/Transfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionsServiceServer).Transfer(ctx, req.(*TransferData))
	}
	return interceptor(ctx, in, info, handler)
}

var _TransactionsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "datapace.TransactionsService",
	HandlerType: (*TransactionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _TransactionsService_CreateUser_Handler,
		},
		{
			MethodName: "Transfer",
			Handler:    _TransactionsService_Transfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transactions.proto",
}
