grafana:
  sidecar:
    dashboards:
      enabled: true
      label: grafana_datasource
	  searchNamespace: monitoring
    datasources:
      enabled: true
      label: grafana_dashboard
	  searchNamespace: monitoring
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/use-regex: "true"
    path: /grafana/?(.*)
    hosts:
      - ndm.datapace.local
    tls:
      - secretName: ndm.datapace.local
        hosts:
          - ndm.datapace.local
  grafana.ini:
    server:
      root_url: http://localhost:3000/grafana
