swagger: "2.0"
info:
  title: Go Auth service
  description: HTTP API for authentication and authorization.
  version: "1.0.0"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /users:
    get:
      summary: Retrieves user info
      tags:
        - users
      parameters:
        - $ref: "#/parameters/Authorization"
      responses:
        200:
          description: User data retrieved.
        403:
          description: Missing or invalid access token provided.
        404:
          description: User does not exist.
        500:
          $ref: "#/responses/ServiceError"
    post:
      summary: Create a user account
      description: |
        User creation is performed with values provided in a request payload.
      tags:
        - users
      parameters:
        - name: user
          description: JSON-formatted document describing the new user.
          in: body
          schema:
            $ref: "#/definitions/User"
          required: true
      responses:
        201:
          description: User created.
        400:
          description: Failed due to malformed JSON.
        409:
          description: Email is already taken.
        500:
          $ref: "#/responses/ServiceError"
    put:
      summary: Updates user info
      description: |
        Update is performed by replacing the current resource data with values
        provided in a request payload. Resource's unique identifier will not be
        affected.
      tags:
        - users
      parameters:
        - name: user
          description: JSON-formatted document describing the new user.
          in: body
          schema:
            $ref: "#/definitions/User"
          required: true
      responses:
        200:
          description: User updated.
        400:
          description: Failed due to malformed JSON.
        403:
          description: Missing or invalid access token provided.
        404:
          description: User does not exist.
        500:
          $ref: "#/responses/ServiceError"
  /tokens:
    post:
      summary: User authentication
      description: |
        Generates an access token when provided with proper credentials.
      tags:
        - authentication
      parameters:
        - name: credentials
          description: JSON-formatted document containing user credentials.
          in: body
          schema:
            $ref: "#/definitions/User"
          required: true
      responses:
        201:
          description: User authenticated.
          schema:
            $ref: "#/definitions/Token"
        400:
          description: |
            Failed due to malformed JSON or using an invalid credentials.
        500:
          $ref: "#/responses/ServiceError"
  /access-requests:
    post:
      summary: Creating and sending access request
      description: |
        Creates new access request and send it to specified receiver.
      tags:
        - access-request
      parameters:
        - name: access-request
          description: Create access request data with user receiver.
          in: body
          schema:
            $ref: "#/definitions/RequestAccessReq"
          required: true
      responses:
        201:
          description: Access request created and sent.
        400:
          description: |
            Failed due to malformed JSON or invalid access request format.
        403:
          description: Missing or invalid access token provided.
        500:
          $ref: "#/responses/ServiceError"
  /access-requests/sent:
    get:
      summary: Fetch access requests that user sent.
      description: Fetch access requests that user already sent.
      tags:
        - access-request
      parameters:
        - $ref: "#/parameters/Authorization"
        - name: state
          description: Search for sent access requests with this state.
          in: query
          type: string
          enum:
            - pending
            - approved
            - revoked
          required: true
      responses:
        200:
          description: Access requests retrieved.
          schema:
            $ref: "#/definitions/AccessRequestsRes"
        400:
          description: Invalid state value.
        403:
          description: Missing or invalid access token provided.
        500:
          $ref: "#/responses/ServiceError"
  /access-requests/received:
    get:
      summary: Fetch access requests that user received.
      description: Fetch access requests that user already received.
      tags:
        - access-request
      parameters:
        - $ref: "#/parameters/Authorization"
        - name: state
          description: Search for received access requests with this state.
          in: query
          type: string
          enum:
            - pending
            - approved
            - revoked
          required: true
      responses:
        200:
          description: Access requests retrieved.
          schema:
            $ref: "#/definitions/AccessRequestsRes"
        400:
          description: Invalid state value.
        403:
          description: Missing or invalid access token provided.
        500:
          $ref: "#/responses/ServiceError"
  /access-requests/{id}/approve:
    put:
      summary: Approves received access request.
      description: Change pending access request state to approved.
      tags:
        - access-request
      parameters:
        - $ref: "#/parameters/Authorization"
        - name: id
          description: Access request ID.
          in: path
          type: string
          required: true
      responses:
        200:
          description: Successfully approved access request.
        403:
          description: Missing or invalid access token provided.
        404:
          description: Access request with specified ID doesn't exist.
        500:
          $ref: "#/responses/ServiceError"
  /access-requests/{id}/reject:
    put:
      summary: Rejects received access request.
      description: Change pending access request state to revoked.
      tags:
        - access-request
      parameters:
        - $ref: "#/parameters/Authorization"
        - name: id
          description: Access request ID.
          in: path
          type: string
          required: true
      responses:
        200:
          description: Successfully rejected access request.
        403:
          description: Missing or invalid access token provided.
        404:
          description: Access request with specified ID doesn't exist.
        500:
          $ref: "#/responses/ServiceError"

parameters:
  Authorization:
    name: Authorization
    description: User access token.
    in: header
    type: string
    required: true

responses:
  ServiceError:
    description: Unexpected server-side error occured.

definitions:
  User:
    type: object
    properties:
      email:
        type: string
        format: email
        example: "test@example.com"
        description: User's email address will be used as its unique identifier
      password:
        type: string
        format: password
        description: Free-form account password used for acquiring auth token(s).
    required:
      - email
      - password
  Token:
    type: object
    properties:
      token:
        type: string
        description: Generated access token.
    required:
      - token
  RequestAccessReq:
    type: object
    properties:
      receiver:
        type: string
        description: ID of user that should receive access request.
  AccessRequestsRes:
    type: array
    items:
      type: object
      properties:
        id:
          type: string
          description: Access request ID.
        sender:
          type: string
          description: ID of the user that sent access request.
        receiver:
          type: string
          description: ID of the user that received access request.
        state:
          type: string
          description: State of the access request.
          enum:
            - pending
            - approved
            - revoked
