loki:
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 100Gi
  config:
    compactor:
      working_directory: /data/loki/boltdb-shipper-compactor
      shared_store: filesystem
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 1h
      retention_delete_worker_count: 150
    limits_config:
      max_global_streams_per_user: 5000
      max_query_length: 2160h
      max_query_parallelism: 32
      retention_period: 2160h # 90 days
promtail:
  syslogService:
    enabled: true
    type: LoadBalancer
    port: 1514
  extraScrapeConfigs:
    - job_name: syslog
      syslog:
        listen_address: 0.0.0.0:1514
        labels:
          job: "syslog"
      relabel_configs:
        - source_labels: ['__syslog_message_hostname']
          target_label: "host"
    - job_name: journal
      journal:
        path: /var/log/journal
        max_age: 12h
        labels:
          job: systemd-journal
      relabel_configs:
        - source_labels: ['__journal__systemd_unit']
          target_label: 'unit'
        - source_labels: ['__journal__hostname']
          target_label: 'hostname'
  extraVolumes:
    - name: journal
      hostPath:
        path: /var/log/journal

  extraVolumeMounts:
    - name: journal
      mountPath: /var/log/journal
      readOnly: true
