# General network config required by fabric-sdk-go

name: "monetasa-dev-network"

# Describe what the target network is/does.
description: "The network which will host Monetasa development network"

# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
version: 2

# The client section used by GO SDK.
client:
  # Which organization does this application instance belong to? The value must be the name of an org
  organization: Org1
  logging:
    level: debug

  # Global configuration for peer, event service and orderer timeouts
  peer:
    timeout:
      connection: 3s
      queryResponse: 45s
      executeTxResponse: 30s
  eventService:
    timeout:
      connection: 3s
      registrationResponse: 3s
  orderer:
    timeout:
      connection: 3s
      response: 5s
  localMspId: Org1MSP

  # Root of the MSP directories with keys and certs. The Membership Service Providers is component that aims to offer an abstraction of a membership operation architecture.
  cryptoconfig:
    path: "${GOPATH}/src/monetasa/examples/crypto-config"

  # Some SDKs support pluggable KV stores, the properties under "credentialStore" are implementation specific
  credentialStore:
    path: "/tmp/monetasa-service-kvs"

     # [Optional]. Specific to the CryptoSuite implementation used by GO SDK. Software-based implementations requiring a key store. PKCS#11 based implementations does not.
    cryptoStore:
      path: "/tmp/monetasa-service-msp"

  # BCCSP config for the client. Used by GO SDK. It's the Blockchain Cryptographic Service Provider.
  # It offers the implementation of cryptographic standards and algorithms.
  BCCSP:
    security:
     enabled: true
     default:
      provider: "SW"
     hashAlgorithm: "SHA2"
     softVerify: true
     ephemeral: false
     level: 256

  tlsCerts:
    systemCertPool: true

# [Optional]. But most apps would have this section so that channel objects can be constructed based on the content below.
# If one of your application is creating channels, you might not use this
channels:
  myc:
    orderers:
      - orderer.monetasa.com

    # Network entity which maintains a ledger and runs chaincode containers in order to perform operations to the ledger. Peers are owned and maintained by members.
    peers:
      peer0.org1.monetasa.com:
        # [Optional]. will this peer be sent transaction proposals for endorsement? The peer must
        # have the chaincode installed. The app can also use this property to decide which peers
        # to send the chaincode install request. Default: true
        endorsingPeer: true

        # [Optional]. will this peer be sent query proposals? The peer must have the chaincode
        # installed. The app can also use this property to decide which peers to send the
        # chaincode install request. Default: true
        chaincodeQuery: true

        # [Optional]. will this peer be sent query proposals that do not require chaincodes, like
        # queryBlock(), queryTransaction(), etc. Default: true
        ledgerQuery: true

        # [Optional]. will this peer be the target of the SDK's listener registration? All peers can

        # Default: true
        eventSource: true

# List of participating organizations in this network
organizations:
  org1:
    mspid: Org1MSP
    #MSPDir: msp
    cryptoPath: "${GOPATH}/src/monetasa/examples/crypto-config/peerOrganizations/org1.monetasa.com/users/Admin@org1.monetasa.com/msp"
    peers:
      - peer0.org1.monetasa.com
    certificateAuthorities:
      - ca.org1.monetasa.com

# List of orderers to send transaction and channel create/update requests to.
# The orderers consent on the order of transactions in a block to be committed to the ledger. For the time being only one orderer is needed.
orderers:
  orderer.monetasa.com:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.monetasa.com
      grpc-max-send-message-length: 15
    tlsCACerts:
      path: "${GOPATH}/src/monetasa/examples/crypto-config/ordererOrganizations/monetasa.com/tlsca/tlsca.monetasa.com-cert.pem"

# List of peers to send various requests to, including endorsement, query and event listener registration.
peers:
  peer0.org1.monetasa.com:
    # this URL is used to send endorsement and query requests
    url: grpcs://localhost:7051
    # this URL is used to connect the EventHub and registering event listeners
    eventUrl: grpcs://localhost:7053
    # These parameters should be set in coordination with the keepalive policy on the server
    grpcOptions:
      ssl-target-name-override: peer0.org1.monetasa.com
      grpc.http2.keepalive_time: 15
    tlsCACerts:
      path: "${GOPATH}/src/monetasa/examples/crypto-config/peerOrganizations/org1.monetasa.com/tlsca/tlsca.org1.monetasa.com-cert.pem"


# Fabric-CA is a special kind of Certificate Authority provided by Hyperledger Fabric which allows certificate management to be done via REST APIs.
certificateAuthorities:
  ca.org1.monetasa.com:
    url: http://localhost:7054
    # the properties specified under this object are passed to the 'http' client verbatim when making the request to the Fabric-CA server
    httpOptions:
      verify: false
    registrar:
      enrollId: admin
      enrollSecret: adminpw
    caName: ca.org1.monetasa.com

entityMatchers:
 peer:
  - pattern: (\w+).org1.monetasa.(\w+)
    urlSubstitutionExp: localhost:7051
    eventUrlSubstitutionExp: localhost:7053
    sslTargetOverrideUrlSubstitutionExp: peer0.org1.monetasa.com
    mappedHost: local.peer0.org1.monetasa.com
orderer:
  - pattern: (\w+).monetasa.(\w+)
    urlSubstitutionExp: localhost:7050
    sslTargetOverrideUrlSubstitutionExp: orderer.monetasa.com
    mappedHost: orderer.monetasa.com
