BCHOSTIP='blockchainserverip'
DATAPACEHOSTIP='k8sserverip'
GITHUBTOKEN='yourgithubtoken'
GITLABUSER='yourgithubusername'
GITLABTOKEN='yourgitlabtoken'
UIHOSTNAME='uihostname'
DPROXYHOSTNAME='dproxyhostname'
