swagger: "2.0"
info:
  title: Datapace Transactions Service
  description: HTTP API for managing transactions and balance.
  version: "1.0.0"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /tokens:
    get:
      summary: Retrieves users balance
      tags:
        - balance
      parameters:
        - $ref: "#/parameters/Authorization"
      responses:
        200:
          description: Users balance retrieved.
          schema:
            $ref: "#/definitions/Balance"
        403:
          description: Missing or invalid access token provided.
        404:
          description: User does not exist.
        500:
          $ref: "#/responses/ServiceError"
  /tokens/buy:
    post:
      summary: Purcheses tokens for user
      tags:
        - tokens
      parameters:
        - $ref: "#/parameters/Authorization"
        - name: amount
          description: |
            JSON-formatted request specifying amount of tokens to be purchesed.
          in: body
          schema:
            $ref: "#/definitions/Amount"
          required: true
      responses:
        200:
          description: User purchesed tokens successfully.
        400:
          description: Failed due to malformed JSON.
        403:
          description: Missing or invalid access token provided.
        415:
          description: Missing or invalid content type.
        500:
          $ref: "#/responses/ServiceError"
  /tokens/withdraw:
    post:
      summary: Sell tokens for real money.
      tags:
        - tokens
      parameters:
        - $ref: "#/parameters/Authorization"
        - name: amount
          description: |
            JSON-formatted request specifying amount of tokens to be withdrawed.
          in: body
          schema:
            $ref: "#/definitions/Amount"
          required: true
      responses:
        200:
          description: User withdrawed tokens successfully.
        400:
          description: Failed due to malformed JSON.
        403:
          description: Missing or invalid access token provided.
        415:
          description: Missing or invalid content type.
        500:
          $ref: "#/responses/ServiceError"

parameters:
  Authorization:
    name: Authorization
    description: User access token.
    in: header
    type: string
    required: true

responses:
  ServiceError:
    description: Unexpected server-side error occured.

definitions:
  Balance:
    type: object
    properties:
      balance:
        type: integer
        description: Current balance.
    required:
      - balance
  Amount:
    type: object
    properties:
      amount:
        type: integer
        description: Amount for purchese.
    required:
      - amount
