# Copyright (c) 2018 Monetasa

version: "3"

services:
  ###
  # Nginx
  ###
  nginx:
    image: nginx:alpine
    container_name: edgex-nginx
    volumes:
      - $PWD/proxy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/proxy/nginx/ssl/certs/mainflux-server.crt:/etc/ssl/certs/mainflux-server.crt
      - $PWD/proxy/nginx/ssl/certs/mainflux-server.key:/etc/ssl/private/mainflux-server.key
      - $PWD/proxy/nginx/ssl/dhparam.pem:/etc/ssl/certs/dhparam.pem
    ports:
      - "80:80"
      - "443:443"
  ###
  # MongoDB
  ###
  monetasa-mongodb:
    image: mongo:latest
    container_name: monetasa-mongodb
    command: --smallfiles --nojournal
    ports:
      - "27017:27017"
  ###
  # Monetasa Auth
  ###
  monetasa-auth:
    build: .
    container_name: monetasa-auth
    links:
      - mongo
    depends_on:
      - monetasa-mongodb
    ports:
      - "8080:8080"
  ###
  # Monetasa dApp
  ###
  monetasa-dapp:
    build: .
    container_name: monetasa-dapp
    links:
      - mongo
    depends_on:
      - monetasa-mongodb
    ports:
      - "8081:8081"
