# Dockerfile for Hyperledger Explorer Docker Image
FROM alpine:3.8
MAINTAINER George Saleh <gesaleh.github.com>

# install maintain tools
#RUN npm install bower grunt-cli graceful-fs@4.1.5 minimatch@3.0.2 -g

# Install dependencies
RUN apk add sudo
RUN apk add postgresql postgresql-contrib
RUN apk add curl wget
#RUN  apk --update add python3  python-software-properties
RUN apk add --no-cache git 


# clone latest code from github
RUN git clone --single-branch -b release-3.4 https://github.com/hyperledger/blockchain-explorer.git

WORKDIR /blockchain-explorer

# Create database for explorer
RUN sudo service postgresql start 
RUN sudo -u postgres psql < app/persistence/postgreSQL/db/explorerpg.sql 
RUN sudo -u postgres psql < app/persistence/postgreSQL/db/updatepg.sql




#RUN echo '{ "allow_root": true }' > .bowerrc

# Modify config.json to update the value of pg host, username, password details.
# If you are building your code for production
# RUN npm install --only=production
RUN npm install && cd client/ && npm install \
     && npm test -- -u --coverage && npm run build
#VOLUME /blockchain-explorer
EXPOSE 8080
CMD ["node", "main.js"]
