# Copyright (c) 2018 Monetasa
version: "2"

services:
  ###
  # MongoDB
  ###
  monetasa-mongodb:
    image: mongo:latest
    container_name: monetasa-mongodb
    command: --smallfiles --nojournal
    ports:
      - "27017:27017"
    networks:
      # Our network is called "monetasa-net"
      - monetasa-net
  ###
  # Monetasa Auth
  ###
  monetasa-auth:
    image: monetasa/auth
    container_name: monetasa-auth
    restart: on-failure
    links:
      - monetasa-mongodb
    depends_on:
      - monetasa-mongodb
    ports:
      - "8080:8080"
    expose:
      - "8081"
    environment:
      - MONETASA_AUTH_MONGO_URL=monetasa-mongodb
      - MONETASA_AUTH_SECRET=monetasa
    volumes:
      - ../config:/go/src/monetasa/config/
    networks:
      # Link to monetasa fabric net
      - fabric_monetasa-bc-net
      - monetasa-net

  ###
  # Monetasa Transactions
  ###
  monetasa-transactions:
    image: monetasa/transactions
    container_name: monetasa-transactions
    restart: on-failure
    ports:
      - "8082:8082"
    expose:
      - "8083"
    environment:
      - MONETASA_TRANSACTIONS_HTTP_PORT=8082
      - MONETASA_TRANSACTIONS_GRPC_PORT=8083
      - MONETASA_AUTH_URL=monetasa-auth:8081
    volumes:
      - ../config:/go/src/monetasa/config/
    networks:
      # Link to monetasa fabric net
      - fabric_monetasa-bc-net
      - monetasa-net

  ###
  # Monetasa UI
  ###
  monetasa-ui:
    image: monetasa/ui
    container_name: monetasa-ui
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      - monetasa-net
  ###
  # Nginx
  ###
  nginx:
    image: nginx:alpine
    container_name: monetasa-nginx
    restart: on-failure
    depends_on:
      - monetasa-auth
      - monetasa-transactions
      - monetasa-ui
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/certs/monetasa.crt:/etc/ssl/certs/monetasa.crt
      - ./ssl/certs/monetasa.key:/etc/ssl/private/monetasa.key
      - ./ssl/dhparam.pem:/etc/ssl/certs/dhparam.pem
    ports:
      - "80:80"
      - "443:443"
    networks:
      # Our network is called "monetasa-net"
      - monetasa-net

networks:
  fabric_monetasa-bc-net:
    external: true
  monetasa-net:
    driver: bridge
