# Copyright (c) 2018 Monetasa
version: "2"

services:
  ###
  # Auth DB
  ###
  monetasa-auth-db:
    image: mongo:latest
    container_name: monetasa-auth-db
    command: --smallfiles --nojournal
    networks:
      # Our network is called "monetasa-net"
      - monetasa-net

  ###
  # Auth service
  ###
  monetasa-auth:
    image: monetasa/auth
    container_name: monetasa-auth
    restart: on-failure
    depends_on:
      - monetasa-auth-db
    ports:
      - "8080:8080"
    expose:
      - "8081"
    environment:
      - MONETASA_AUTH_DB_URL=monetasa-auth-db
      - MONETASA_TRANSACTIONS_URL=monetasa-transactions:8083
      - MONETASA_AUTH_SECRET=monetasa
    networks:
      - monetasa-net

  ###
  # Transactions DB
  ###
  monetasa-transactions-db:
    image: mongo:latest
    container_name: monetasa-transactions-db
    command: --smallfiles --nojournal
    networks:
      - monetasa-net

  ###
  # Transactions service
  ###
  monetasa-transactions:
    image: monetasa/transactions
    container_name: monetasa-transactions
    restart: on-failure
    depends_on:
      - monetasa-auth
      - monetasa-transactions-db
    ports:
      - "8082:8082"
    expose:
      - "8083"
    environment:
      - MONETASA_TRANSACTIONS_HTTP_PORT=8082
      - MONETASA_TRANSACTIONS_GRPC_PORT=8083
      - MONETASA_TRANSACTIONS_DB_URL=monetasa-transactions-db
      - MONETASA_TRANSACTIONS_FABRIC_ADMIN=Admin@org1.monetasa.com
      - MONETASA_AUTH_URL=monetasa-auth:8081
    volumes:
      - ../config:/go/src/monetasa/config/
    networks:
      # Link to monetasa fabric net
      - fabric_monetasa-bc-net
      - monetasa-net

  ###
  # Streams DB
  ###
  monetasa-streams-db:
    image: mongo:latest
    container_name: monetasa-streams-db
    command: --smallfiles --nojournal
    networks:
      - monetasa-net

  ###
  # Streams service
  ###
  monetasa-streams:
    image: monetasa/streams:latest
    container_name: monetasa-streams
    depends_on:
      - monetasa-streams-db
    ports:
      - 8084:8084
    expose:
      - 8085
    environment:
      MONETASA_STREAMS_HTTP_PORT: 8084
      MONETASA_STREAMS_GRPC_PORT: 8085
      MONETASA_STREAMS_DB_URL: monetasa-streams-db
      MONETASA_STREAMS_DB_NAME: streams
      MONETASA_AUTH_URL: monetasa-auth:8081
    networks:
      - monetasa-net

  ###
  # Subscriptions DB
  ###
  monetasa-subscriptions-db:
    image: mongo:latest
    container_name: monetasa-subscriptions-db
    command: --smallfiles --nojournal
    networks:
      - monetasa-net

  ###
  # Subscriptions service
  ###
  monetasa-subscriptions:
    image: monetasa/subscriptions:latest
    container_name: monetasa-subscriptions
    depends_on:
      - monetasa-subscriptions-db
    ports:
      - 8086:8086
    environment:
      MONETASA_SUBSCRIPTIONS_PORT: 8086
      MONETASA_SUBSCRIPTIONS_DB_URL: monetasa-subscriptions-db
      MONETASA_SUBSCRIPTIONS_DB_NAME: subscriptions
      MONETASA_AUTH_URL: monetasa-auth:8081
      MONETASA_STREAMS_URL: monetasa-streams:8085
      MONETASA_TRANSACTIONS_URL: monetasa-transactions:8083
    networks:
      - monetasa-net

  ###
  # Monetasa UI
  ###
  monetasa-ui:
    image: monetasa/ui
    container_name: monetasa-ui
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      - monetasa-net
  ###
  # Nginx
  ###
  nginx:
    image: nginx:alpine
    container_name: monetasa-nginx
    restart: on-failure
    depends_on:
      - monetasa-auth
      - monetasa-transactions
      - monetasa-streams
      - monetasa-ui
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/certs/monetasa.crt:/etc/ssl/certs/monetasa.crt
      - ./ssl/certs/monetasa.key:/etc/ssl/private/monetasa.key
      - ./ssl/dhparam.pem:/etc/ssl/certs/dhparam.pem
    ports:
      - "80:80"
      - "443:443"
    networks:
      # Our network is called "monetasa-net"
      - monetasa-net

networks:
  fabric_monetasa-bc-net:
    external: true
  monetasa-net:
    driver: bridge
