# Copyright (c) 2018 Datapace
version: "2"

services:
  ###
  # Auth DB
  ###
  datapace-auth-db:
    image: mongo:latest
    container_name: datapace-auth-db
    command: --nojournal
    volumes:
      - ./auth-data:/data/db
    networks:
      # Our network is called "datapace-net"
      - datapace-net

  ###
  # Auth service
  ###
  datapace-auth:
    image: registry.gitlab.com/drasko/datapace-docker/auth
    container_name: datapace-auth
    restart: on-failure
    depends_on:
      - datapace-auth-db
    ports:
      - "8080:8080"
      - "8081:8081"
    expose:
      - "8081"
    environment:
      - DATAPACE_AUTH_DB_URL=datapace-auth-db
      - DATAPACE_TRANSACTIONS_URL=datapace-transactions:8083
      - DATAPACE_ACCESS_CONTROL_URL=datapace-access-control:8091
      - DATAPACE_AUTH_SECRET=datapace
      - DATAPACE_ADMIN_EMAIL=admin@datapace.com
      - DATAPACE_ADMIN_PASSWORD=admin
    networks:
      - datapace-net

  ###
  # Transactions DB
  ###
  datapace-transactions-db:
    image: mongo:latest
    container_name: datapace-transactions-db
    command: --nojournal
    volumes:
      - ./transactions-data:/data/db
    networks:
      - datapace-net

  ###
  # Transactions service
  ###
  datapace-transactions:
    image: registry.gitlab.com/drasko/datapace-docker/transactions
    container_name: datapace-transactions
    restart: on-failure
    depends_on:
      - datapace-auth
      - datapace-transactions-db
    ports:
      - "8082:8082"
    expose:
      - "8083"
    environment:
      - DATAPACE_TRANSACTIONS_HTTP_PORT=8082
      - DATAPACE_TRANSACTIONS_GRPC_PORT=8083
      - DATAPACE_TRANSACTIONS_DB_URL=datapace-transactions-db
      - DATAPACE_TRANSACTIONS_FABRIC_ADMIN=Admin@org1.datapace.com
      - DATAPACE_AUTH_URL=datapace-auth:8081
      - DATAPACE_STREAMS_URL=datapace-streams:8085
      - DATAPACE_CONFIG=/config
    volumes:
      - ../config:/config
      - ./datapace-service-kvs:/tmp/datapace-service-kvs
      - ./datapace-service-msp:/tmp/datapace-service-msp
    networks:
      # Link to datapace fabric net
      - fabric_datapace-bc-net
      - datapace-net

  ###
  # Streams DB
  ###
  datapace-streams-db:
    image: mongo:latest
    container_name: datapace-streams-db
    command: --nojournal
    volumes:
      - ./streams-data:/data/db
    networks:
      - datapace-net

  ###
  # Streams service
  ###
  datapace-streams:
    image: registry.gitlab.com/drasko/datapace-docker/streams:latest
    container_name: datapace-streams
    depends_on:
      - datapace-streams-db
      - datapace-auth
      - datapace-access-control
      - datapace-executions
    ports:
      - 8084:8084
    expose:
      - 8085
    environment:
      - DATAPACE_STREAMS_HTTP_PORT=8084
      - DATAPACE_STREAMS_GRPC_PORT=8085
      - DATAPACE_STREAMS_DB_URL=datapace-streams-db
      - DATAPACE_STREAMS_DB_NAME=streams
      - DATAPACE_AUTH_URL=datapace-auth:8081
      - DATAPACE_EXECUTIONS_URL=datapace-executions:8089
      - DATAPACE_ACCESS_CONTROL_URL=datapace-access-control:8091
      - DATAPACE_TERMS_URL=datapace-terms:8093
      - GOOGLE_APPLICATION_CREDENTIALS=/big-query/DigiSense-1987a4981f2e.json
      - DATAPACE_KUBEFLOW_URL=https://kubeflow.datapace.io/
    volumes:
      - ../config/big-query:/big-query
    networks:
      - datapace-net

  ###
  # Subscriptions DB
  ###
  datapace-subscriptions-db:
    image: mongo:latest
    container_name: datapace-subscriptions-db
    command: --nojournal
    ports:
      - 27017:27017
    volumes:
      - ./subscriptions-data:/data/db
    networks:
      - datapace-net
  ###
  # Subscriptions service
  ###
  datapace-subscriptions:
    image: registry.gitlab.com/drasko/datapace-docker/subscriptions:latest
    container_name: datapace-subscriptions
    depends_on:
      - datapace-subscriptions-db
      - datapace-streams
      - datapace-dproxy
    ports:
      - 8086:8086
    environment:
      - DATAPACE_SUBSCRIPTIONS_PORT=8086
      - DATAPACE_SUBSCRIPTIONS_DB_URL=datapace-subscriptions-db
      - DATAPACE_SUBSCRIPTIONS_DB_NAME=subscriptions
      - DATAPACE_AUTH_URL=datapace-auth:8081
      - DATAPACE_STREAMS_URL=datapace-streams:8085
      - DATAPACE_TRANSACTIONS_URL=datapace-transactions:8083
      - DATAPACE_PROXY_URL=http://datapace-dproxy:8087
      - GOOGLE_APPLICATION_CREDENTIALS=/big-query/DigiSense-1987a4981f2e.json
    volumes:
      - ../config/big-query:/big-query
    networks:
      - datapace-net

  ###
  # Terms DB
  ###
  datapace-terms-db:
    image: mongo:latest
    container_name: datapace-terms-db
    command: --nojournal
    ports:
      - 27020:27017
    volumes:
      - ./terms-data:/data/db
    networks:
      - datapace-net

  ###
  # Terms service
  ###
  datapace-terms:
    image: registry.gitlab.com/drasko/datapace-docker/terms:latest
    container_name: datapace-terms
    depends_on:
      - datapace-terms-db
      - datapace-auth
    environment:
      - DATAPACE_TERMS_HTTP_PORT=8092
      - DATAPACE_TERMS_GRPC_PORT=8093
      - DATAPACE_TERMS_DB_URL=datapace-terms-db
      - DATAPACE_TERMS_FABRIC_ADMIN=Admin@org1.datapace.com
      - DATAPACE_AUTH_URL=datapace-auth:8081
      - DATAPACE_CONFIG=/config
    volumes:
      - ../config:/config
      - ./datapace-service-kvs:/tmp/datapace-service-kvs
      - ./datapace-service-msp:/tmp/datapace-service-msp
    networks:
      - datapace-net
      - fabric_datapace-bc-net
    ports:
      - 8092:8092

  ###
  # Executions DB
  ###
  datapace-executions-db:
    image: mongo:latest
    container_name: datapace-executions-db
    command: --nojournal
    volumes:
      - ./executions-data:/data/db
    networks:
      # Our network is called "datapace-net"
      - datapace-net

  ###
  # Executions serivce
  ###
  datapace-executions:
    image: registry.gitlab.com/drasko/datapace-docker/executions:latest
    container_name: datapace-executions
    depends_on:
      - datapace-executions-db
      - datapace-auth
    ports:
      - 8088:8088
    expose:
      - 8089
    environment:
      - DATAPACE_EXECUTIONS_HTTP_PORT=8088
      - DATAPACE_EXECUTIONS_GRPC_PORT=8089
      - DATAPACE_EXECUTIONS_DB_URL=datapace-executions-db
      - DATAPACE_AUTH_URL=datapace-auth:8081
      - DATAPACE_SUBSCRIPTIONS_URL=http://datapace-subscriptions:8086
      - DATAPACE_WWH_CATALOG_URL=http://localhost:31222 # instead of localhost place docker host IP
      - DATAPACE_WWH_DAEMON_URL=localhost:32222 # same here (check it with docker exec -it datapace-executions route)
      - DATAPACE_WWH_TOKEN=v61rSpnp89
      - DATAPACE_WWH_USERNAME=admin1
      - DATAPACE_WWH_PASSWORD=password01
      - DATAPACE_KUBEFLOW_ACTIVE=true
      - DATAPACE_KUBEFLOW_URL=https://kubeflow.datapace.io
      - DATAPACE_KUBEFLOW_STATUS_INTERVAL=10
      - DATAPACE_AI_SYSTEM=argo
      - DATAPACE_ARGO_URL=https://kubeflow.datapace.io
    networks:
      - datapace-net

  ###
  # Access Control DB
  ###
  datapace-access-control-db:
    image: mongo:latest
    container_name: datapace-access-control-db
    command: --nojournal
    volumes:
      - ./access-control-data:/data/db
    networks:
      # Our network is called "datapace-net"
      - datapace-net

  ###
  # Access Control service
  ###
  datapace-access-control:
    image: registry.gitlab.com/drasko/datapace-docker/access-control
    container_name: datapace-access-control
    restart: on-failure
    depends_on:
      - datapace-access-control-db
      - datapace-auth
    ports:
      - 8090:8090
    expose:
      - 8091
    environment:
      - DATAPACE_ACCESS_CONTROL_HTTP_PORT=8090
      - DATAPACE_ACCESS_CONTROL_GRPC_PORT=8091
      - DATAPACE_ACCESS_CONTROL_DB_URL=datapace-access-control-db
      - DATAPACE_ACCESS_CONTROL_FABRIC_ADMIN=Admin@org1.datapace.com
      - DATAPACE_AUTH_URL=datapace-auth:8081
      - DATAPACE_CONFIG=/config
    volumes:
      - ../config:/config
      - ./datapace-service-kvs:/tmp/datapace-service-kvs
      - ./datapace-service-msp:/tmp/datapace-service-msp
    networks:
      # Link to datapace fabric net
      - fabric_datapace-bc-net
      - datapace-net

  datapace-dproxy:
    image: registry.gitlab.com/drasko/datapace-docker/dproxy
    container_name: datapace-dproxy
    environment:
      - DATAPACE_DPROXY_DB_HOST=datapace-dproxy-db
      - DATAPACE_LOCAL_FS_ROOT=/data
      - DATAPACE_DPROXY_ENCRYPTION_KEY=W0JD00gEAGUDV6UI0+16iVRx8p+PQx79ahGlBwhWz/g=
    depends_on:
      - datapace-dproxy-db
    volumes:
      - ./dproxy-data:/data

    ports:
      - "8087:8087"
    restart: on-failure
    networks:
      - datapace-net

  datapace-dproxy-db:
    image: mongo:latest
    container_name: datapace-dproxy-db
    command: --nojournal
    ports:
      - 27021:27017
    volumes:
      - ./dproxy-data:/data/db
    networks:
      - datapace-net

  ###
  # Datapace UI
  ###
  datapace-ui:
    image: registry.gitlab.com/drasko/datapace-docker/ui
    container_name: datapace-ui
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      - datapace-net
  ###
  # Nginx
  ###
  nginx:
    image: nginx:alpine
    container_name: datapace-nginx
    restart: on-failure
    depends_on:
      - datapace-auth
      - datapace-transactions
      - datapace-streams
      - datapace-executions
      - datapace-ui
    volumes:
      - ./nginx/nginx.exec.conf:/etc/nginx/nginx.conf
      - ./ssl/certs/datapace.crt:/etc/ssl/certs/datapace.crt
      - ./ssl/certs/datapace.key:/etc/ssl/private/datapace.key
      - ./ssl/dhparam.pem:/etc/ssl/certs/dhparam.pem
    ports:
      - "80:80"
      - "443:443"
    networks:
      # Our network is called "datapace-net"
      - datapace-net

networks:
  fabric_datapace-bc-net:
    external: true
  datapace-net:
    driver: bridge
