apiVersion: v2
name: datapace
description: Helm chart for Datapace deployment. More at https://github.com/datapace/datapace.
type: application
version: 0.1.0
appVersion: 0.1.0
dependencies:
  - name: mongodb
    version: "7.10.10"
    repository: "https://charts.bitnami.com/bitnami"
