### Send POST to get token
POST http://localhost:9090/api/register
Content-Type: application/json

{
  "url": "http://10.10.10.10/test.png",
  "ttl": 60
}
> {%
    client.global.set("auth_token", response.body.token);
%}


###

### Send GET to fetch resource
GET http://localhost:9090/http
Authorization: {{auth_token}}

###