# Copyright (c) 2018 Datapace
version: "3"

services:
  ###
  # Executions DB
  ###
  datapace-executions-db:
    logging:
      driver: fluentd
      options:
        fluentd-address: ${LOGSERVER}:24224
        tag: docker.{{.ID}}
  ###
  # Executions serivce
  ###
  datapace-executions:
    logging:
      driver: fluentd
      options:
        fluentd-address: ${LOGSERVER}:24224
        tag: docker.{{.ID}}
