alertmanagerFiles:
  alertmanager.yml:
    global:
      resolve_timeout: 5m
      slack_api_url: 'https://hooks.slack.com/services/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'

    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 24h
      receiver: 'slack-notification'
    receivers:
    - name: 'slack-notification'
      slack_configs:
      - channel: '#monitoring'
        send_resolved: true
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
          {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
            {{" "}}(
            {{- with .CommonLabels.Remove .GroupLabels.Names }}
              {{- range $index, $label := .SortedPairs -}}
                {{ if $index }}, {{ end }}
                {{- $label.Name }}="{{ $label.Value -}}"
              {{- end }}
            {{- end -}}
            )
          {{- end }}
        text: >-
          {{ range .Alerts -}}
          *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
          *Description:* {{ .Annotations.description }}
          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
    #- name: 'email'
    #  email_configs:
    #  - to: 'p.sukumar@nokia.com'
    #    from: 'pksukumar7@gmail.com'
    #    smarthost: smtp.gmail.com:587
    #    auth_username: 'pksukumar7@gmail.com'
    #    auth_identity: 'pksukumar7@gmail.com'
    #    auth_password: ''
