alertmanagerFiles:
  alertmanager.yml:
    global:
      resolve_timeout: 5m
      slack_api_url: 'https://hooks.slack.com/services/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'
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 24h
      receiver: 'NHC'
      routes:
        - receiver: 'NDM-L4'
          match_re:
            severity: critical|warning
          continue: true
        - receiver: 'NHC'
          match_re:
            severity: critical|warning
          continue: true
    receivers:
    - name: 'NDM-L4'
      slack_configs:
      - channel: '#monitoring'
        send_resolved: true
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
          {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
            {{" "}}(
            {{- with .CommonLabels.Remove .GroupLabels.Names }}
              {{- range $index, $label := .SortedPairs -}}
                {{ if $index }}, {{ end }}
                {{- $label.Name }}="{{ $label.Value -}}"
              {{- end }}
            {{- end -}}
            )
          {{- end }}
        text: >-
          {{ range .Alerts -}}
          *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
          *Description:* {{ .Annotations.description }}
          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
    - name: 'NHC'
      email_configs:
      - to: 'i_ext_nhc_support@nokia.com'
        from: 'p.sukumar@nokia.com'
        smarthost: smtp-relay.sendinblue.com:587
        auth_username: 'p.sukumar@nokia.com'
        auth_identity: 'NDM Alerting'
        auth_password: 'BRb1kNq3WwspdQZ4'
