
# SPDX-License-Identifier: Apache-2.0
version: '2.1'

volumes:
  expgdata:
  walletstore:

networks:
  explorer.datapace.com:
    external:
      name: fabric_datapace-bc-net

services:

  explorerdb.mynetwork.com:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.explorer.datapace.com
    hostname: explorerdb.explorer.datapace.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    volumes:
      - ./postgreSQL/db/createdb.sh:/docker-entrypoint-initdb.d/createdb.sh
      - ../expgdata:/var/lib/postgresql/data
    networks:
      - explorer.datapace.com

  explorer.mynetwork.com:
    image: hyperledger/explorer:1.0.0-rc1
    container_name: explorer.explorer.datapace.com
    hostname: explorer.explorer.datapace.com
    environment:
      - DATABASE_HOST=explorerdb.explorer.datapace.com
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ../explorer/artifacts/config.json:/opt/explorer/app/platform/fabric/config.json
      - ../explorer/artifacts/connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ../explorer/artifacts/pgconfig.json:/opt/app/persistence/postgreSQL/db/pgconfig.json
      - ../../config/crypto-config:/tmp/crypto
    command: sh -c "sleep 16&& node /opt/explorer/main.js && tail -f /dev/null"
    ports:
      - 9090:8080
    networks:
      - explorer.datapace.com
