
# SPDX-License-Identifier: Apache-2.0
version: '2.1'

volumes:
  expgdata:
  walletstore:

networks:
  explorer.datapace.com:
    external:
      name: fabric_datapace-bc-net

services:

  explorerdb.datapace.com:
    image: hyperledger/explorer-db:1.1.3
    container_name: explorerdb.explorer.datapace.com
    hostname: explorerdb.explorer.datapace.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./postgreSQL/db/createdb.sh:/docker-entrypoint-initdb.d/createdb.sh
      - ./postgreSQL/db/explorerpg.sql:/opt/explorerpg.sql
      - ./postgreSQL/db/updatepg.sql:/opt/updatepg.sql
      - ./postgreSQL/db/processenv.js:/opt/processenv.js
      - ../expgdata:/var/lib/postgresql/data
    networks:
      - explorer.datapace.com

  explorer.datapace.com:
    image: hyperledger/explorer:1.1.3
    container_name: explorer.datapace.com
    hostname: explorer.datapace.com
    environment:
      - DATABASE_HOST=explorerdb.explorer.datapace.com
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - DISCOVERY_AS_LOCALHOST=false
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
    volumes:
      - ../explorer/artifacts/config.json:/opt/explorer/app/platform/fabric/config.json
      - ../explorer/artifacts/connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ../explorer/artifacts/pgconfig.json:/opt/app/persistence/postgreSQL/db/pgconfig.json
      - ../../config/crypto-config:/tmp/crypto
      - ../walletstore:/opt/explorer/wallet
    ports:
      - 9090:8080
    depends_on:
      explorerdb.datapace.com:
        condition: service_healthy
    networks:
      - explorer.datapace.com
