version: '2'

networks:
  explorer-net:
    external:
      name: fabric_datapace-bc-net

services: 

  explorer-db:
    image: postgres
    container_name: fabric-explorer-db
    ports:
      - "5532:5432"
    volumes:
      - ../explorer/artifacts/explorerpg.sql:/docker-entrypoint-initdb.d/explorerpg.sql
      - ../explorer/artifacts/updatepg.sql:/docker-entrypoint-initdb.d/updatepg.sql
    networks:
      - explorer-net

  explorer:
    image: datapace/hyperledger-explorer
    container_name: fabric-explorer
    hostname: explorer
    restart: always
    volumes:
      - ../explorer/artifacts/config.json:/blockchain-explorer/app/platform/fabric/config.json
      - ../explorer/artifacts/pgconfig.json:/blockchain-explorer/app/persistence/postgreSQL/db/pgconfig.json
      - ../../config/crypto-config:/blockchain-explorer/examples/net1/crypto-network/crypto-config
    ports:
      - "9090:8080"
    networks:
      - explorer-net
    depends_on:
      - explorer-db

