// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/offers.proto

package offers

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetOfferPriceRequest struct {
	StreamId             string   `protobuf:"bytes,1,opt,name=streamId,proto3" json:"streamId,omitempty"`
	BuyerId              string   `protobuf:"bytes,2,opt,name=buyerId,proto3" json:"buyerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOfferPriceRequest) Reset()         { *m = GetOfferPriceRequest{} }
func (m *GetOfferPriceRequest) String() string { return proto.CompactTextString(m) }
func (*GetOfferPriceRequest) ProtoMessage()    {}
func (*GetOfferPriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8439a939726828c3, []int{0}
}

func (m *GetOfferPriceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOfferPriceRequest.Unmarshal(m, b)
}
func (m *GetOfferPriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOfferPriceRequest.Marshal(b, m, deterministic)
}
func (m *GetOfferPriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOfferPriceRequest.Merge(m, src)
}
func (m *GetOfferPriceRequest) XXX_Size() int {
	return xxx_messageInfo_GetOfferPriceRequest.Size(m)
}
func (m *GetOfferPriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOfferPriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOfferPriceRequest proto.InternalMessageInfo

func (m *GetOfferPriceRequest) GetStreamId() string {
	if m != nil {
		return m.StreamId
	}
	return ""
}

func (m *GetOfferPriceRequest) GetBuyerId() string {
	if m != nil {
		return m.BuyerId
	}
	return ""
}

type GetOfferPriceResponse struct {
	OfferPrice           uint64   `protobuf:"varint,1,opt,name=offerPrice,proto3" json:"offerPrice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOfferPriceResponse) Reset()         { *m = GetOfferPriceResponse{} }
func (m *GetOfferPriceResponse) String() string { return proto.CompactTextString(m) }
func (*GetOfferPriceResponse) ProtoMessage()    {}
func (*GetOfferPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8439a939726828c3, []int{1}
}

func (m *GetOfferPriceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOfferPriceResponse.Unmarshal(m, b)
}
func (m *GetOfferPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOfferPriceResponse.Marshal(b, m, deterministic)
}
func (m *GetOfferPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOfferPriceResponse.Merge(m, src)
}
func (m *GetOfferPriceResponse) XXX_Size() int {
	return xxx_messageInfo_GetOfferPriceResponse.Size(m)
}
func (m *GetOfferPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOfferPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOfferPriceResponse proto.InternalMessageInfo

func (m *GetOfferPriceResponse) GetOfferPrice() uint64 {
	if m != nil {
		return m.OfferPrice
	}
	return 0
}

func init() {
	proto.RegisterType((*GetOfferPriceRequest)(nil), "offers.GetOfferPriceRequest")
	proto.RegisterType((*GetOfferPriceResponse)(nil), "offers.GetOfferPriceResponse")
}

func init() {
	proto.RegisterFile("proto/offers.proto", fileDescriptor_8439a939726828c3)
}

var fileDescriptor_8439a939726828c3 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x4f, 0x4b, 0x4b, 0x2d, 0x2a, 0xd6, 0x03, 0x73, 0x84, 0xd8, 0x20, 0x3c, 0x25,
	0x1f, 0x2e, 0x11, 0xf7, 0xd4, 0x12, 0x7f, 0x10, 0x27, 0xa0, 0x28, 0x33, 0x39, 0x35, 0x28, 0xb5,
	0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x48, 0x8a, 0x8b, 0xa3, 0xb8, 0xa4, 0x28, 0x35, 0x31, 0xd7, 0x33,
	0x45, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xce, 0x17, 0x92, 0xe0, 0x62, 0x4f, 0x2a, 0xad,
	0x4c, 0x2d, 0xf2, 0x4c, 0x91, 0x60, 0x02, 0x4b, 0xc1, 0xb8, 0x4a, 0xe6, 0x5c, 0xa2, 0x68, 0xa6,
	0x15, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0xc9, 0x71, 0x71, 0xe5, 0xc3, 0x45, 0xc1, 0x06, 0xb2,
	0x04, 0x21, 0x89, 0x18, 0xc5, 0x73, 0xf1, 0x82, 0x75, 0x15, 0x07, 0xa7, 0x16, 0x95, 0x65, 0x26,
	0xa7, 0x0a, 0xf9, 0x71, 0xf1, 0xa2, 0x98, 0x24, 0x24, 0xa3, 0x07, 0x75, 0x3f, 0x36, 0xe7, 0x4a,
	0xc9, 0xe2, 0x90, 0x85, 0x58, 0xaf, 0xc4, 0xe0, 0xa4, 0x1d, 0xa5, 0x99, 0x9e, 0x59, 0x92, 0x51,
	0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x9f, 0x92, 0x58, 0x92, 0x58, 0x90, 0x98, 0x9c, 0x8a, 0x60,
	0x20, 0x07, 0x51, 0x12, 0x1b, 0x98, 0x67, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x17, 0xa6,
	0x34, 0x39, 0x01, 0x00, 0x00,
}
