// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package executions

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ExecutionsServiceClient is the client API for ExecutionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExecutionsServiceClient interface {
	CreateAlgorithm(ctx context.Context, in *Algorithm, opts ...grpc.CallOption) (*empty.Empty, error)
	CreateDataset(ctx context.Context, in *Dataset, opts ...grpc.CallOption) (*empty.Empty, error)
}

type executionsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutionsServiceClient(cc grpc.ClientConnInterface) ExecutionsServiceClient {
	return &executionsServiceClient{cc}
}

func (c *executionsServiceClient) CreateAlgorithm(ctx context.Context, in *Algorithm, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/datapace.ExecutionsService/CreateAlgorithm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionsServiceClient) CreateDataset(ctx context.Context, in *Dataset, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/datapace.ExecutionsService/CreateDataset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecutionsServiceServer is the server API for ExecutionsService service.
// All implementations must embed UnimplementedExecutionsServiceServer
// for forward compatibility
type ExecutionsServiceServer interface {
	CreateAlgorithm(context.Context, *Algorithm) (*empty.Empty, error)
	CreateDataset(context.Context, *Dataset) (*empty.Empty, error)
	mustEmbedUnimplementedExecutionsServiceServer()
}

// UnimplementedExecutionsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedExecutionsServiceServer struct {
}

func (*UnimplementedExecutionsServiceServer) CreateAlgorithm(context.Context, *Algorithm) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAlgorithm not implemented")
}
func (*UnimplementedExecutionsServiceServer) CreateDataset(context.Context, *Dataset) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDataset not implemented")
}
func (*UnimplementedExecutionsServiceServer) mustEmbedUnimplementedExecutionsServiceServer() {}

func RegisterExecutionsServiceServer(s *grpc.Server, srv ExecutionsServiceServer) {
	s.RegisterService(&_ExecutionsService_serviceDesc, srv)
}

func _ExecutionsService_CreateAlgorithm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Algorithm)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionsServiceServer).CreateAlgorithm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datapace.ExecutionsService/CreateAlgorithm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionsServiceServer).CreateAlgorithm(ctx, req.(*Algorithm))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionsService_CreateDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Dataset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionsServiceServer).CreateDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datapace.ExecutionsService/CreateDataset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionsServiceServer).CreateDataset(ctx, req.(*Dataset))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExecutionsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "datapace.ExecutionsService",
	HandlerType: (*ExecutionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAlgorithm",
			Handler:    _ExecutionsService_CreateAlgorithm_Handler,
		},
		{
			MethodName: "CreateDataset",
			Handler:    _ExecutionsService_CreateDataset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/executions.proto",
}
