// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/executions.proto

package executions

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Algorithm struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Algorithm) Reset()         { *m = Algorithm{} }
func (m *Algorithm) String() string { return proto.CompactTextString(m) }
func (*Algorithm) ProtoMessage()    {}
func (*Algorithm) Descriptor() ([]byte, []int) {
	return fileDescriptor_12d26af948d194f2, []int{0}
}

func (m *Algorithm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Algorithm.Unmarshal(m, b)
}
func (m *Algorithm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Algorithm.Marshal(b, m, deterministic)
}
func (m *Algorithm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Algorithm.Merge(m, src)
}
func (m *Algorithm) XXX_Size() int {
	return xxx_messageInfo_Algorithm.Size(m)
}
func (m *Algorithm) XXX_DiscardUnknown() {
	xxx_messageInfo_Algorithm.DiscardUnknown(m)
}

var xxx_messageInfo_Algorithm proto.InternalMessageInfo

func (m *Algorithm) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Algorithm) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Algorithm) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Dataset struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Dataset) Reset()         { *m = Dataset{} }
func (m *Dataset) String() string { return proto.CompactTextString(m) }
func (*Dataset) ProtoMessage()    {}
func (*Dataset) Descriptor() ([]byte, []int) {
	return fileDescriptor_12d26af948d194f2, []int{1}
}

func (m *Dataset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dataset.Unmarshal(m, b)
}
func (m *Dataset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dataset.Marshal(b, m, deterministic)
}
func (m *Dataset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dataset.Merge(m, src)
}
func (m *Dataset) XXX_Size() int {
	return xxx_messageInfo_Dataset.Size(m)
}
func (m *Dataset) XXX_DiscardUnknown() {
	xxx_messageInfo_Dataset.DiscardUnknown(m)
}

var xxx_messageInfo_Dataset proto.InternalMessageInfo

func (m *Dataset) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Dataset) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterType((*Algorithm)(nil), "datapace.Algorithm")
	proto.RegisterMapType((map[string]string)(nil), "datapace.Algorithm.MetadataEntry")
	proto.RegisterType((*Dataset)(nil), "datapace.Dataset")
	proto.RegisterMapType((map[string]string)(nil), "datapace.Dataset.MetadataEntry")
}

func init() {
	proto.RegisterFile("proto/executions.proto", fileDescriptor_12d26af948d194f2)
}

var fileDescriptor_12d26af948d194f2 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0xbd, 0x4e, 0xf3, 0x40,
	0x10, 0xfc, 0xce, 0xf9, 0x80, 0x64, 0x51, 0x80, 0x1c, 0x28, 0x8a, 0x4c, 0x41, 0x70, 0x95, 0x86,
	0xb3, 0x14, 0x1a, 0x44, 0x40, 0xe2, 0xcf, 0x25, 0x4d, 0xe8, 0xe8, 0xce, 0xf6, 0xe2, 0x9c, 0xb0,
	0x7d, 0x96, 0x73, 0x8e, 0xf0, 0x73, 0xe4, 0x31, 0x78, 0x49, 0xe4, 0xf3, 0x1f, 0x10, 0x28, 0xe9,
	0xd6, 0xe3, 0x9d, 0xdd, 0xd9, 0x99, 0x83, 0x61, 0x92, 0x4a, 0x25, 0x6d, 0x7c, 0x43, 0x2f, 0x53,
	0x42, 0xc6, 0x4b, 0xa6, 0x01, 0xda, 0xf5, 0xb9, 0xe2, 0x09, 0xf7, 0xd0, 0x3c, 0x0e, 0xa4, 0x0c,
	0x42, 0xb4, 0x35, 0xee, 0x66, 0x2f, 0x36, 0x46, 0x89, 0xca, 0xcb, 0x36, 0xeb, 0x9d, 0x40, 0xef,
	0x36, 0x0c, 0x64, 0x2a, 0xd4, 0x22, 0xa2, 0x7b, 0x60, 0x08, 0x7f, 0x44, 0xc6, 0x64, 0xd2, 0x9b,
	0x1b, 0xc2, 0xa7, 0x14, 0xfe, 0xc7, 0x3c, 0xc2, 0x91, 0xa1, 0x11, 0x5d, 0xd3, 0x6b, 0xe8, 0x46,
	0xa8, 0x78, 0x31, 0x7e, 0xd4, 0x19, 0x77, 0x26, 0xbb, 0xd3, 0x53, 0x56, 0xef, 0x62, 0xcd, 0x28,
	0xf6, 0x58, 0xf5, 0x38, 0xb1, 0x4a, 0xf3, 0x79, 0x43, 0x31, 0x67, 0xd0, 0xff, 0xf2, 0x8b, 0x1e,
	0x40, 0xe7, 0x15, 0xf3, 0x6a, 0x69, 0x51, 0xd2, 0x23, 0xd8, 0x5a, 0xf1, 0x30, 0xab, 0xd7, 0x96,
	0x1f, 0x97, 0xc6, 0x05, 0xb1, 0xd6, 0x04, 0x76, 0x1e, 0xb8, 0xe2, 0x4b, 0x54, 0x1b, 0x5a, 0x67,
	0x9f, 0x74, 0x19, 0x5a, 0xd7, 0x49, 0xab, 0xab, 0x22, 0xfd, 0x89, 0xaa, 0xe9, 0x9a, 0xc0, 0xc0,
	0x69, 0xfc, 0x7f, 0xc2, 0x74, 0x25, 0x3c, 0xa4, 0x37, 0xb0, 0x7f, 0x9f, 0x22, 0x57, 0xd8, 0xda,
	0x7b, 0xf8, 0x83, 0x51, 0xe6, 0x90, 0x95, 0xf9, 0xb0, 0x3a, 0x1f, 0xe6, 0x14, 0xf9, 0x58, 0xff,
	0xe8, 0x15, 0xf4, 0xcb, 0x09, 0xf5, 0xc9, 0x83, 0x8d, 0x83, 0x7e, 0x67, 0xdf, 0xd9, 0xcf, 0x67,
	0x81, 0x50, 0x8b, 0xcc, 0x65, 0x9e, 0x8c, 0xec, 0x9a, 0xd8, 0x16, 0xdf, 0xdf, 0x8d, 0xbb, 0xad,
	0x91, 0xf3, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x93, 0xaa, 0x5a, 0x52, 0x02, 0x00, 0x00,
}
