// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/dproxy.proto

package dproxy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DproxyServiceClient is the client API for DproxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DproxyServiceClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type dproxyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDproxyServiceClient(cc grpc.ClientConnInterface) DproxyServiceClient {
	return &dproxyServiceClient{cc}
}

func (c *dproxyServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/dproxy.DproxyService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DproxyServiceServer is the server API for DproxyService service.
// All implementations must embed UnimplementedDproxyServiceServer
// for forward compatibility
type DproxyServiceServer interface {
	List(context.Context, *ListRequest) (*ListResponse, error)
	mustEmbedUnimplementedDproxyServiceServer()
}

// UnimplementedDproxyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDproxyServiceServer struct {
}

func (UnimplementedDproxyServiceServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedDproxyServiceServer) mustEmbedUnimplementedDproxyServiceServer() {}

// UnsafeDproxyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DproxyServiceServer will
// result in compilation errors.
type UnsafeDproxyServiceServer interface {
	mustEmbedUnimplementedDproxyServiceServer()
}

func RegisterDproxyServiceServer(s grpc.ServiceRegistrar, srv DproxyServiceServer) {
	s.RegisterService(&DproxyService_ServiceDesc, srv)
}

func _DproxyService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DproxyServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dproxy.DproxyService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DproxyServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DproxyService_ServiceDesc is the grpc.ServiceDesc for DproxyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DproxyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dproxy.DproxyService",
	HandlerType: (*DproxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _DproxyService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dproxy.proto",
}
