// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.9
// source: proto/transactions.proto

package transactions

import (
	common "github.com/datapace/datapace/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferData struct {
	StreamID             string   `protobuf:"bytes,1,opt,name=streamID,proto3" json:"streamID,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Value                uint64   `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	DateTime             string   `protobuf:"bytes,5,opt,name=dateTime,proto3" json:"dateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

	StreamID string `protobuf:"bytes,1,opt,name=streamID,proto3" json:"streamID,omitempty"`
	From     string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To       string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Value    uint64 `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *TransferData) Reset() {
	*x = TransferData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_transactions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferData) ProtoMessage() {}

func (x *TransferData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transactions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferData.ProtoReflect.Descriptor instead.
func (*TransferData) Descriptor() ([]byte, []int) {
	return file_proto_transactions_proto_rawDescGZIP(), []int{0}
}

func (x *TransferData) GetStreamID() string {
	if x != nil {
		return x.StreamID
	}
	return ""
}

func (x *TransferData) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TransferData) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TransferData) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (m *TransferData) GetDateTime() string {
	if m != nil {
		return m.DateTime
	}
	return ""
}

func init() {
	proto.RegisterType((*TransferData)(nil), "datapace.TransferData")
}

var file_proto_transactions_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_transactions_proto_goTypes = []interface{}{
	(*TransferData)(nil),  // 0: datapace.TransferData
	(*common.ID)(nil),     // 1: datapace.ID
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_proto_transactions_proto_depIdxs = []int32{
	1, // 0: datapace.TransactionsService.CreateUser:input_type -> datapace.ID
	0, // 1: datapace.TransactionsService.Transfer:input_type -> datapace.TransferData
	2, // 2: datapace.TransactionsService.CreateUser:output_type -> google.protobuf.Empty
	2, // 3: datapace.TransactionsService.Transfer:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

var fileDescriptor_1edb37854b34f19b = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xbf, 0x4f, 0xf3, 0x30,
	0x10, 0x86, 0xbf, 0xe4, 0x4b, 0x51, 0xb0, 0x2a, 0x06, 0x83, 0x2a, 0x2b, 0x2c, 0x55, 0xa7, 0x4e,
	0x8e, 0xf8, 0x31, 0x32, 0x41, 0x18, 0xba, 0x96, 0xb0, 0xb0, 0x5d, 0xd2, 0x4b, 0x88, 0x54, 0xe7,
	0x22, 0xe7, 0x52, 0x89, 0x8d, 0x95, 0xff, 0x1a, 0xc5, 0x56, 0x68, 0x25, 0xc4, 0x76, 0xef, 0x23,
	0xbf, 0xaf, 0xf4, 0xc8, 0x42, 0x75, 0x96, 0x98, 0x52, 0xb6, 0xd0, 0xf6, 0x50, 0x72, 0x43, 0x6d,
	0xaf, 0x1d, 0x92, 0xf1, 0x0e, 0x18, 0x3a, 0x28, 0x31, 0xb9, 0xae, 0x89, 0xea, 0x3d, 0xa6, 0x8e,
	0x17, 0x43, 0x95, 0xa2, 0xe9, 0xf8, 0xc3, 0x3f, 0x4b, 0xa4, 0x1f, 0x28, 0xc9, 0x18, 0x6a, 0x3d,
	0x5b, 0x7d, 0x06, 0x62, 0x9e, 0x8f, 0x8b, 0x15, 0xda, 0x0c, 0x18, 0x64, 0x22, 0xe2, 0x9e, 0x2d,
	0x82, 0xd9, 0x64, 0x2a, 0x58, 0x06, 0xeb, 0xf3, 0xed, 0x4f, 0x96, 0x52, 0x44, 0x95, 0x25, 0xa3,
	0x42, 0xc7, 0xdd, 0x2d, 0x2f, 0x44, 0xc8, 0xa4, 0xfe, 0x3b, 0x12, 0x32, 0xc9, 0x2b, 0x31, 0x3b,
	0xc0, 0x7e, 0x40, 0x15, 0x2d, 0x83, 0x75, 0xb4, 0xf5, 0x61, 0x5c, 0xdd, 0x01, 0x63, 0xde, 0x18,
	0x54, 0x33, 0xbf, 0x3a, 0xe5, 0xdb, 0xaf, 0x40, 0x5c, 0xe6, 0x27, 0x52, 0x2f, 0x68, 0x0f, 0x4d,
	0x89, 0xf2, 0x5e, 0x88, 0x27, 0x8b, 0xc0, 0xf8, 0xda, 0xa3, 0x95, 0x73, 0x3d, 0x49, 0xea, 0x4d,
	0x96, 0x2c, 0xb4, 0x17, 0xd5, 0x93, 0xa8, 0x7e, 0x1e, 0x45, 0x57, 0xff, 0xe4, 0x83, 0x88, 0x27,
	0x1f, 0xb9, 0x38, 0x76, 0x4e, 0x1d, 0xff, 0x6e, 0x3f, 0xde, 0xbc, 0xa5, 0x75, 0xc3, 0xef, 0x43,
	0xa1, 0x4b, 0x32, 0xe9, 0xd4, 0x3e, 0x1e, 0xbf, 0xbf, 0xa0, 0x38, 0x73, 0xec, 0xee, 0x3b, 0x00,
	0x00, 0xff, 0xff, 0x62, 0x58, 0x90, 0x51, 0x9f, 0x01, 0x00, 0x00,
}
