apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ include "datapace.fullname" . }}-{{ .Values.auth.suffix }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ include "datapace.fullname" . }}-{{ .Values.auth.suffix }}"
  minReplicas: {{ .Values.auth.hpa.minReplicas }}
  maxReplicas: {{ .Values.auth.hpa.maxReplicas }}
  metrics:
  {{- range $i, $resource := $.Values.auth.hpa.resources }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: {{ $resource.target.type }}
        {{ $resource.target.name }}: {{ $resource.target.value }}
  {{- end }}