apiVersion: v1
kind: PersistentVolume
metadata:
  name: kvs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: keystore
  local:
    path: {{ .Values.keystore.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: keystore
          operator: In
          values:
          - "true"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kvs
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: keystore
  resources:
    requests:
      storage: 1Gi