{{- range $i, $org := .Values.OrdererOrgs }}
{{- range $i, $host := $org.Specs }}
{{- $commonName := printf "%s.%s" $host.Hostname $org.Domain }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: hlf-orderer--{{ $org.Name | lower }}--{{ $host.Hostname | lower }}-tlsca
  labels:
    orgName: {{ $org.Name }}
    commonName: {{ $commonName }}
data:
  tlsca.{{ $org.Domain }}-cert.pem: |-
      {{ $.Files.Get (printf "crypto-config/ordererOrganizations/%s/tlsca/tlsca.%s-cert.pem" $org.Domain $org.Domain ) | b64enc }}
---
{{- end }} {{- /* org.Specs */ -}}
{{- end }} {{- /* Orgs */ -}}
