{{- range $i, $org := .Values.PeerOrgs }}
{{- range $peerIndex := until ($org.Template.Count | int) }}
{{- $peer := (printf "peer%s" ($peerIndex | toString)) }}
{{- $vars:= dict "firstKey" true }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: hlf-peer--{{ $org.Name | lower }}--{{ $peer | lower }}-tlsca
  labels:
    orgName: {{ $org.Name }}
    peerName: {{ $peer }}
data:
  tlscacert.pem: |-
      {{ $.Files.Get (printf "crypto-config/peerOrganizations/%s/peers/%s.%s/msp/tlscacerts/tlsca.%s-cert.pem" $org.Domain $peer $org.Domain $org.Domain ) | b64enc }}
---
{{- end }} {{- /* Peers */ -}}
{{- end }} {{- /* Orgs */ -}}
