apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "datapace.fullname" . }}-{{ .Values.terms.suffix }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "datapace.fullname" . }}
      component: {{ .Values.terms.suffix }}
  template:
    metadata:
      labels:
        app: {{ include "datapace.fullname" . }}
        component: {{ .Values.terms.suffix }}
    spec:
      imagePullSecrets:
        - name: registrykey
      serviceAccountName: {{ include "datapace.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - env:
            - name: DATAPACE_TERMS_HTTP_PORT
              value: "{{ .Values.terms.service.port.http }}"
            - name: DATAPACE_TERMS_GRPC_PORT
              value: "{{ .Values.terms.service.port.grpc }}"
            - name: DATAPACE_TERMS_DB_URL
              value: "{{- printf "%s-%s" .Release.Name "datapace-mongodb"}}"
            - name: DATAPACE_TERMS_FABRIC_ADMIN
              value: "Admin@org1.datapace.com"
            - name: DATAPACE_AUTH_URL
              value: "{{ include "datapace.fullname" . }}-{{ .Values.auth.suffix }}:{{ .Values.auth.service.port.grpc }}"
            - name: DATAPACE_CONFIG
              value: "/tmp/config"
          name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ default .Values.defaults.image.repository .Values.terms.image.repository }}/{{ .Values.terms.image.name }}:{{ default .Values.defaults.image.tag .Values.terms.image.tag }}"
          imagePullPolicy: {{default .Values.defaults.image.pullPolicy .Values.terms.image.pullPolicy}}
          ports:
            - name: http
              containerPort: {{ .Values.terms.service.port.http }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /version
              port: {{ .Values.terms.service.port.http }}
          readinessProbe:
            httpGet:
              path: /version
              port: {{ .Values.terms.service.port.http }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: kvs
              mountPath: "/tmp/datapace-service-kvs"
            - name: msp
              mountPath: "/tmp/datapace-service-msp"
            - name: config
              mountPath: "/tmp/config"
      volumes:
        - name: kvs
          persistentVolumeClaim:
            claimName: kvs
        - name: msp
          persistentVolumeClaim:
            claimName: msp
        - name: config
          persistentVolumeClaim:
            claimName: config
      hostAliases:
        - ip: {{ .Values.bc.ip }}
          hostnames:
          {{- range .Values.bc.hostnames }}
          - {{ . | quote }}
          {{- end }}
