{{- if .Values.ui.ingress.enabled -}}
{{- $fullName := include "datapace.fullname" . -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: "{{ (printf "%s-%s" $fullName .Values.ui.suffix) }}"
  labels:
    {{- include "datapace.labels" . | nindent 4 }}
  {{- with .Values.dproxy.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ui.ingress.tls }}
  tls:
  {{- range .Values.ui.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ui.ingress.host }}
      http:
        paths:
          - path: /
          {{ if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            backend:
              service:
                name: "{{ (printf "%s-%s" $fullName .Values.ui.suffix) }}"
                port: 
                  number: {{ .Values.ui.service.port }}
          {{ else }}
            backend:
              serviceName: "{{ (printf "%s-%s" $fullName .Values.ui.suffix) }}"
              servicePort: {{ .Values.ui.service.port }}
          {{ end }}
{{- end }}
