{{- if .Values.ui.ingress.enabled -}}
{{- $fullName := include "datapace.fullname" . -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: "{{ (printf "%s-%s" $fullName .Values.ui.suffix) }}"
  labels:
    {{- include "datapace.labels" . | nindent 4 }}
spec:
{{- if .Values.ui.ingress.tls }}
  tls:
  {{- range .Values.ui.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ui.ingress.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: "{{ (printf "%s-%s" $fullName .Values.ui.suffix) }}"
              servicePort: {{ .Values.ui.service.port }}
{{- end }}
