{{- if .Values.ca.ingress.enabled -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: hlf-ca--ingress
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
{{- range $i, $org := .Values.PeerOrgs }}
  - host: hlf-ca-{{ $org.Name | lower }}.{{ $.Values.ingress.parentDomain }}
    http:
      paths:
      - path: /
      {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
        pathType: Prefix
        backend:
          service:
            name: hlf-ca--{{ $org.Name | lower }}
            port: 
              number: 7054
      {{- else }}
        backend:
          serviceName: hlf-ca--{{ $org.Name | lower }}
          servicePort: 7054
      {{- end }}
{{- end }}
  tls:
  - hosts:
{{- range $i, $org := .Values.PeerOrgs }}
    - hlf-ca-{{ $org.Name | lower }}.{{ $.Values.ingress.parentDomain }}
{{- end }}
    secretName: hlf-ca--ingress-tls
{{- end }} {{- /* if ingress.enabled */ -}}
