{{- if or .Values.backup.enabled .Values.restore.enabled }}
{{- range $i, $org := .Values.PeerOrgs }}

apiVersion: v1
kind: Service
metadata:
  name: hlf-ca-rsync--{{ $org.Name | lower }}
  labels:
    name: hlf-ca-rsync--{{ $org.Name | lower }}
spec:
  type: ClusterIP
  selector:
    app: hlf-ca--{{ $org.Name | lower }}
  ports:
  - protocol: TCP
    port: 873
    name: rsync
---
{{- end }} {{- /* Orgs */ -}}
{{- end }} {{- /* if backup/restore enabled */ -}}
