{{- if .Values.peer.ingress.enabled -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: hlf-peer--ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    {{- range $key, $value := .Values.peer.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
{{- range $i, $org := .Values.PeerOrgs }}
{{- range $peerIndex := until ($org.Template.Count | int) }}
{{- $peer := (printf "peer%s" ($peerIndex | toString)) }}
  - host: {{ $peer }}.{{ $org.Domain }}
    http:
      paths:
      - path: /
      {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
        pathType: Prefix
        backend:
          service:
            name: hlf-peer--{{ $org.Name | lower }}--{{ $peer | lower }}
            port: 
              number: 7051
      {{- else }}
        backend:
          serviceName: hlf-peer--{{ $org.Name | lower }}--{{ $peer | lower }}
          servicePort: 7051
      {{- end }}
{{- end }} {{- /* Peers */ -}}
{{- end }} {{- /* Orgs */ -}}{{""}}
{{- end }} {{- /* if ingress.enabled */ -}}
