# This role binding is needed for argo. Argo needs permission to patch, list, get, watch the pods.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: fabric-admin
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: fabric-rbac
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: fabric-admin
  apiGroup: rbac.authorization.k8s.io
