{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: rbac.authorization.k8s.io/v1
{{- else -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: fabric-admin
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "patch"]

---
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: rbac.authorization.k8s.io/v1
{{- else -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
kind: RoleBinding
metadata:
  name: fabric-rbac
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: fabric-admin
  apiGroup: rbac.authorization.k8s.io
