# General network config required by fabric-sdk-go

name: "datapace-dev-network"

# Describe what the target network is/does.
description: "The network which will host Datapace development network"

# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
version: 2

# The client section used by GO SDK.
client:
  # Which organization does this application instance belong to? The value must be the name of an org
  organization: Org1
  logging:
    level: debug

  # Global configuration for peer, event service and orderer timeouts
  peer:
    timeout:
      connection: 3s
      queryResponse: 45s
      executeTxResponse: 30s
  eventService:
    timeout:
      connection: 3s
      registrationResponse: 3s
  orderer:
    timeout:
      connection: 3s
      response: 5s
  localMspId: Org1MSP

  # Root of the MSP directories with keys and certs. The Membership Service Providers is component that aims to offer an abstraction of a membership operation architecture.
  cryptoconfig:
    path: "${DATAPACE_CONFIG}/crypto-config"

  # Some SDKs support pluggable KV stores, the properties under "credentialStore" are implementation specific
  credentialStore:
    path: "/tmp/datapace-service-kvs"

     # [Optional]. Specific to the CryptoSuite implementation used by GO SDK. Software-based implementations requiring a key store. PKCS#11 based implementations does not.
    cryptoStore:
      path: "/tmp/datapace-service-msp"

  # BCCSP config for the client. Used by GO SDK. It's the Blockchain Cryptographic Service Provider.
  # It offers the implementation of cryptographic standards and algorithms.
  BCCSP:
    security:
     enabled: true
     default:
      provider: "SW"
     hashAlgorithm: "SHA2"
     softVerify: true
     ephemeral: false
     level: 256

  tlsCerts:
    systemCertPool: true

# [Optional]. But most apps would have this section so that channel objects can be constructed based on the content below.
# If one of your application is creating channels, you might not use this
channels:
  datapacechannel:
    # orderers:
    #   - orderer.datapace.com
    #
    # Network entity which maintains a ledger and runs chaincode containers in order to perform operations to the ledger. Peers are owned and maintained by members.
    peers:
      peer0.org1.datapace.com:
        # [Optional]. will this peer be sent transaction proposals for endorsement? The peer must
        # have the chaincode installed. The app can also use this property to decide which peers
        # to send the chaincode install request. Default: true
        endorsingPeer: true

        # [Optional]. will this peer be sent query proposals? The peer must have the chaincode
        # installed. The app can also use this property to decide which peers to send the
        # chaincode install request. Default: true
        chaincodeQuery: true

        # [Optional]. will this peer be sent query proposals that do not require chaincodes, like
        # queryBlock(), queryTransaction(), etc. Default: true
        ledgerQuery: true

        # [Optional]. will this peer be the target of the SDK's listener registration? All peers can

        # Default: true
        eventSource: true
        
# List of participating organizations in this network
organizations:
  org1:
    mspid: Org1MSP
    cryptoPath: "${DATAPACE_CONFIG}/crypto-config/peerOrganizations/org1.datapace.com/users/Admin@org1.datapace.com/msp"
    peers:
      - peer0.org1.datapace.com
    certificateAuthorities:
      - ca.org1.datapace.com

# List of orderers to send transaction and channel create/update requests to.
# The orderers consent on the order of transactions in a block to be committed to the ledger. For the time being only one orderer is needed.
orderers:
  orderer.datapace.com:
    url: grpcs://orderer.datapace.com:7050
    grpcOptions:
      ssl-target-name-override: orderer.datapace.com
      grpc-max-send-message-length: 15
    tlsCACerts:
      path: "${DATAPACE_CONFIG}/crypto-config/ordererOrganizations/datapace.com/tlsca/tlsca.datapace.com-cert.pem"

# List of peers to send various requests to, including endorsement, query and event listener registration.
peers:
  peer0.org1.datapace.com:
    # this URL is used to send endorsement and query requests
    url: grpcs://peer0.org1.datapace.com:7051
    # this URL is used to connect the EventHub and registering event listeners
    eventUrl: grpcs://peer0.org1.datapace.com:7053
    # These parameters should be set in coordination with the keepalive policy on the server
    grpcOptions:
      ssl-target-name-override: peer0.org1.datapace.com
      grpc.http2.keepalive_time: 15
    tlsCACerts:
      path: "${DATAPACE_CONFIG}/crypto-config/peerOrganizations/org1.datapace.com/tlsca/tlsca.org1.datapace.com-cert.pem"


# Fabric-CA is a special kind of Certificate Authority provided by Hyperledger Fabric which allows certificate management to be done via REST APIs.
certificateAuthorities:
  ca.org1.datapace.com:
    # Change this according to your fabric-ca URL
    url: http://ca.org1.datapace.com:7054
    # the properties specified under this object are passed to the 'http' client verbatim when making the request to the Fabric-CA server
    tlsCACerts:
      #   # Comma-Separated list of paths
      path: "${DATAPACE_CONFIG}/crypto-config/peerOrganizations/org1.datapace.com/tlsca/tlsca.org1.datapace.com-cert.pem"
    httpOptions:
      verify: false
    registrar:
      enrollId: Admin@org1.datapace.com
      enrollSecret: adminpw
    caName: ca.org1.datapace.com

entityMatchers:
  peer:
    - pattern: (\w+).org1.datapace.(\w+)
      urlSubstitutionExp: 'peer0.org1.datapace.com:7051'
      eventUrlSubstitutionExp: 'peer0.org1.datapace.com:7053'
      sslTargetOverrideUrlSubstitutionExp: peer0.org1.datapace.com
      mappedHost: peer0.org1.datapace.com
  orderer:
    - pattern: (\w+).datapace.(\w+)
      urlSubstitutionExp: orderer.datapace.com:7050
      sslTargetOverrideUrlSubstitutionExp: orderer.datapace.com
      mappedHost: orderer.datapace.com
  certificateAuthorities:
    - pattern: (\w*).org1.datapace.com(\w*)
      urlSubstitutionExp:
      mappedHost: ca.org1.datapace.com
