# cryptogen config which generate crypto-config folder

OrdererOrgs:
#---------------------------------------------------------
# Orderer
# --------------------------------------------------------
- Name: Orderer
  Domain: datapace.com
  # ------------------------------------------------------
  # "Specs" - See PeerOrgs below for complete description
  # -----------------------------------------------------
  Specs:
    - Hostname: orderer
# -------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
 # ------------------------------------------------------
PeerOrgs:
# -----------------------------------------------------
# DatapaceOrg
# ----------------------------------------------------
- Name: DatapaceOrg
  Domain: org1.datapace.com
  EnableNodeOUs: false
  Template:
    Count: 1
  Users:
    Count: 1
