version: '2'

services:
  ca-base:
      container_name: fabric-ca-server
      image: hyperledger/fabric-ca:1.4
      ports:
         - "7054:7054"
      environment:
         - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
