version: '2'

networks:
  datapace-bc-net:
    driver: bridge

services:
  # Fabric tools
  cli-upgrade:
    container_name: cli-upgrade
    image: hyperledger/fabric-tools:2.2
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - GOBIN=/opt/gopath/bin
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=cli
      # peer0 from Org1 is the default for this CLI container
      - CORE_PEER_ADDRESS=peer0.org1.datapace.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      # Reflect peer0 name, org1 name and our company's domain
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.datapace.com/peers/peer0.org1.datapace.com/tls/server.crt
      # Reflect peer0 name, org1 name and our company's domain
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.datapace.com/peers/peer0.org1.datapace.com/tls/server.key
      # Reflect peer0 name, org1 name and our company's domain
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.datapace.com/peers/peer0.org1.datapace.com/tls/ca.crt
      # Reflect peer0 name, org1 name and our company's domain
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.datapace.com/users/Admin@org1.datapace.com/msp
      # This cert is needed for invoking chaincode methods
      - ORDERER_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/datapace.com/users/Admin@datapace.com/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    # On start we are provisioning the network
    command: /bin/bash -c 'scripts/upgrade.sh ${VERSION} ${CHAINCODE}'
    volumes:
        - /var/run/:/host/var/run/
        - ../../chaincode/:/opt/gopath/src/github.com/chaincode
        - ../../config/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
        - ./artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/artifacts
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
    networks:
      - datapace-bc-net
